MODULE COPY_GEOMETRY_MOD

USE TYPE_GEOMETRY, ONLY : GEOMETRY

INTERFACE COPY
MODULE PROCEDURE COPY_GEOMETRY
END INTERFACE

CONTAINS

SUBROUTINE COPY_GEOMETRY (YD)
USE COPY_TCSGEOM_MOD
USE COPY_TCSGLEG_MOD
USE COPY_TDIM_MOD
USE COPY_TDIMV_MOD
USE COPY_TEDIM_MOD
USE COPY_TEGEO_MOD
USE COPY_TEGSL_MOD
USE COPY_TELBC_GEO_MOD
USE COPY_TEMMP_MOD
USE COPY_TGEM_MOD
USE COPY_TGSGEOM_MOD
USE COPY_THSLMER_MOD
USE COPY_TLAP_MOD
USE COPY_TLEP_MOD
USE COPY_TMP_MOD
USE COPY_TOROG_MOD
USE COPY_TSPGEOM_MOD
USE COPY_TSTA_MOD
USE COPY_TVAB_MOD
USE COPY_TVERTICAL_GEOM_MOD
USE COPY_TVETA_MOD
USE COPY_TVFE_MOD
USE COPY_TVSLETA_MOD
USE COPY_TVSPLIP_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN) :: YD
INTEGER :: J1

CALL COPY (YD%YRVERT_GEOM)

!$acc enter data create (YD%YRVAB)
CALL COPY (YD%YRVAB)
!$acc enter data attach (YD%YRVAB)

!$acc enter data create (YD%YRVETA)
CALL COPY (YD%YRVETA)
!$acc enter data attach (YD%YRVETA)

!$acc enter data create (YD%YRVFE)
CALL COPY (YD%YRVFE)
!$acc enter data attach (YD%YRVFE)

CALL COPY (YD%YRSTA)

CALL COPY (YD%YRLAP)

CALL COPY (YD%YRCSGLEG)

CALL COPY (YD%YRDIM)

CALL COPY (YD%YRDIMV)

CALL COPY (YD%YRMP)

CALL COPY (YD%YRGEM)

CALL COPY (YD%YRVSPLIP)

CALL COPY (YD%YRVSLETA)

CALL COPY (YD%YRHSLMER)

!$acc enter data create (YD%YRCSGEOM)
DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
  CALL COPY (YD%YRCSGEOM (J1))
ENDDO
!$acc enter data attach (YD%YRCSGEOM)

CALL COPY (YD%YRCSGEOM_NB)

!$acc enter data create (YD%YRGSGEOM)
DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
  CALL COPY (YD%YRGSGEOM (J1))
ENDDO
!$acc enter data attach (YD%YRGSGEOM)

CALL COPY (YD%YRGSGEOM_NB)

!$acc enter data create (YD%YRCSGEOMAD)
DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
  CALL COPY (YD%YRCSGEOMAD (J1))
ENDDO
!$acc enter data attach (YD%YRCSGEOMAD)

CALL COPY (YD%YRCSGEOMAD_NB)

!$acc enter data create (YD%YRGSGEOMAD)
DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
  CALL COPY (YD%YRGSGEOMAD (J1))
ENDDO
!$acc enter data attach (YD%YRGSGEOMAD)

CALL COPY (YD%YRGSGEOMAD_NB)

!$acc enter data create (YD%YROROG)
DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
  CALL COPY (YD%YROROG (J1))
ENDDO
!$acc enter data attach (YD%YROROG)

CALL COPY (YD%YSPGEOM)

CALL COPY (YD%YVABIO)

CALL COPY (YD%YREDIM)

CALL COPY (YD%YREGEO)

CALL COPY (YD%YREMP)

CALL COPY (YD%YRELAP)

CALL COPY (YD%YREGSL)

!$acc enter data create (YD%YRELBC_GEO)
CALL COPY (YD%YRELBC_GEO)
!$acc enter data attach (YD%YRELBC_GEO)

END SUBROUTINE

END MODULE
