MODULE COPY_MODEL_DYNAMICS_TYPE_MOD

USE MODEL_DYNAMICS_MOD, ONLY : MODEL_DYNAMICS_TYPE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_DYNAMICS_TYPE
END INTERFACE

CONTAINS

SUBROUTINE COPY_MODEL_DYNAMICS_TYPE (YD)
USE COPY_SL_STRUCT_MOD
USE COPY_TCCO_MOD
USE COPY_TDYN_MOD
USE COPY_TEDYN_MOD
USE COPY_TLSCAW_MOD
USE COPY_TPTRGPPC_MOD
USE COPY_TPTRSLB1_MOD
USE COPY_TPTRSLB15_MOD
USE COPY_TPTRSLB2_MOD
USE COPY_TRSCAW_MOD
USE COPY_TSCO_MOD
USE COPY_TSLREP_MOD
USE COPY_TSPNG_MOD
USE COPY_TTNH_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN) :: YD

CALL COPY (YD%YRDYN)

CALL COPY (YD%YREDYN)

CALL COPY (YD%YRSPNG)

CALL COPY (YD%YRPTRGPPC)

CALL COPY (YD%YYTLSCAW)

CALL COPY (YD%YYTLSCAWH)

CALL COPY (YD%YYTRSCAW)

CALL COPY (YD%YYTRSCAWH)

CALL COPY (YD%YYTSCO)

CALL COPY (YD%YYTCCO)

CALL COPY (YD%YRSLREP)

CALL COPY (YD%YRPTRSLB1)

CALL COPY (YD%YRPTRSLB2)

CALL COPY (YD%YRPTRSLB15)

CALL COPY (YD%YRTNH)

CALL COPY (YD%YRSL)

CALL COPY (YD%YRAD)

END SUBROUTINE

END MODULE
