MODULE COPY_TLSCAW_MOD

USE INTDYNSL_MOD, ONLY : TLSCAW

INTERFACE COPY
MODULE PROCEDURE COPY_TLSCAW
END INTERFACE

CONTAINS

SUBROUTINE COPY_TLSCAW (YD)

IMPLICIT NONE
TYPE (TLSCAW), INTENT (IN) :: YD

!$acc update device (YD%M_WDLO)

!$acc update device (YD%M_WDLAT)

!$acc update device (YD%M_WDVER)

!$acc update device (YD%M_WDLOMAD)

!$acc update device (YD%M_WDLAMAD)

!$acc update device (YD%M_WDVERMAD)

!$acc update device (YD%NDIM)

END SUBROUTINE

END MODULE
