MODULE LOAD_TRIP_MOD

USE YOMRIP, ONLY : TRIP

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRIP
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TRIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRIP), INTENT (OUT) :: YD

READ (KLUN) YD%NSTART
READ (KLUN) YD%NSTOP
READ (KLUN) YD%CSTOP
READ (KLUN) YD%NSTADD
READ (KLUN) YD%NSTASS
READ (KLUN) YD%NFOST
READ (KLUN) YD%RSTATI
READ (KLUN) YD%RTIMTR
READ (KLUN) YD%RHGMT
READ (KLUN) YD%REQTIM
READ (KLUN) YD%RSOVR
READ (KLUN) YD%RDEASO
READ (KLUN) YD%RDECLI
READ (KLUN) YD%RWSOVR
READ (KLUN) YD%RIP0
READ (KLUN) YD%RCODEC
READ (KLUN) YD%RSIDEC
READ (KLUN) YD%RCOVSR
READ (KLUN) YD%RSIVSR
READ (KLUN) YD%RCODECN
READ (KLUN) YD%RSIDECN
READ (KLUN) YD%RCOVSRN
READ (KLUN) YD%RSIVSRN
READ (KLUN) YD%RCODECF
READ (KLUN) YD%RSIDECF
READ (KLUN) YD%RCOVSRF
READ (KLUN) YD%RSIVSRF
READ (KLUN) YD%TSTEP
READ (KLUN) YD%TDT
READ (KLUN) YD%RDTSA
READ (KLUN) YD%RDTSA2
READ (KLUN) YD%RDTS62
READ (KLUN) YD%RDTS22
READ (KLUN) YD%RTDT
READ (KLUN) YD%RDECLU
READ (KLUN) YD%RTMOLT
READ (KLUN) YD%RIP0LU
READ (KLUN) YD%RCODECLU
READ (KLUN) YD%RSIDECLU
READ (KLUN) YD%RCOVSRLU
READ (KLUN) YD%RSIVSRLU
END SUBROUTINE


END MODULE
