MODULE LOAD_TCSGLEG_MOD

USE YOMLEG, ONLY : TCSGLEG

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCSGLEG
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TCSGLEG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGLEG), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LR1MU2, LR1MUA, LR1MUI, LR1QM2, LRACTHE, LRLATI, LRLATIG, LRMU, LRSQM2, LRW
READ (KLUN) LRW
IF (LRW) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RW (IL1(1):IU1(1)))
  READ (KLUN) YD%RW
ENDIF
READ (KLUN) LRMU
IF (LRMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMU (IL1(1):IU1(1)))
  READ (KLUN) YD%RMU
ENDIF
READ (KLUN) LR1MU2
IF (LR1MU2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1MU2 (IL1(1):IU1(1)))
  READ (KLUN) YD%R1MU2
ENDIF
READ (KLUN) LR1MUI
IF (LR1MUI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1MUI (IL1(1):IU1(1)))
  READ (KLUN) YD%R1MUI
ENDIF
READ (KLUN) LR1MUA
IF (LR1MUA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1MUA (IL1(1):IU1(1)))
  READ (KLUN) YD%R1MUA
ENDIF
READ (KLUN) LRSQM2
IF (LRSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSQM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%RSQM2
ENDIF
READ (KLUN) LR1QM2
IF (LR1QM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%R1QM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%R1QM2
ENDIF
READ (KLUN) LRACTHE
IF (LRACTHE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RACTHE (IL1(1):IU1(1)))
  READ (KLUN) YD%RACTHE
ENDIF
READ (KLUN) LRLATIG
IF (LRLATIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATIG (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATIG
ENDIF
READ (KLUN) LRLATI
IF (LRLATI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATI (IL1(1):IU1(1)))
  READ (KLUN) YD%RLATI
ENDIF
END SUBROUTINE


END MODULE
