MODULE LOAD_MODEL_GENERAL_CONF_TYPE_MOD

USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_GENERAL_CONF_TYPE
END INTERFACE

CONTAINS

SUBROUTINE LOAD_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE LOAD_TDIMF_MOD
USE LOAD_TRIP_MOD
USE LOAD_TYPE_GFLD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (OUT) :: YD

NULLIFY (YD%GEOM)
CALL LOAD (KLUN, YD%YRDIMF)
CALL LOAD (KLUN, YD%YGFL)
CALL LOAD (KLUN, YD%YRRIP)
END SUBROUTINE


END MODULE
