MODULE LOAD_TYPE_GFL_NAML_MOD

USE YOM_YGFL, ONLY : TYPE_GFL_NAML

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_GFL_NAML
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TYPE_GFL_NAML (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFL_NAML), INTENT (OUT) :: YD

READ (KLUN) YD%CNAME
READ (KLUN) YD%IGRBCODE
READ (KLUN) YD%NREQIN
READ (KLUN) YD%REFVALI
READ (KLUN) YD%LREQOUT
READ (KLUN) YD%LGPINGP
READ (KLUN) YD%LGP
READ (KLUN) YD%LSP
READ (KLUN) YD%LCDERS
READ (KLUN) YD%LT9
READ (KLUN) YD%LT1
READ (KLUN) YD%LT5
READ (KLUN) YD%LPHY
READ (KLUN) YD%LPT
READ (KLUN) YD%LTRAJIO
READ (KLUN) YD%LDIAG
READ (KLUN) YD%LPC
READ (KLUN) YD%LADV
READ (KLUN) YD%LADV5
READ (KLUN) YD%LINTLIN
READ (KLUN) YD%LTDIABLIN
READ (KLUN) YD%LHORTURB
READ (KLUN) YD%LQM
READ (KLUN) YD%LQMH
READ (KLUN) YD%LQM3D
READ (KLUN) YD%LQML3D
READ (KLUN) YD%LSLHD
READ (KLUN) YD%LCOMAD
READ (KLUN) YD%LHV
READ (KLUN) YD%LVSPLIP
READ (KLUN) YD%NCOUPLING
READ (KLUN) YD%REFVALC
READ (KLUN) YD%NCOUPLO4
READ (KLUN) YD%LASSIM
READ (KLUN) YD%IGRIBDV
READ (KLUN) YD%IGRIBTC
READ (KLUN) YD%IGRIBSFC
READ (KLUN) YD%IGRIBDIAG
READ (KLUN) YD%LDIFF
READ (KLUN) YD%LCONV
READ (KLUN) YD%LNEGFIX
READ (KLUN) YD%LMASSFIX
READ (KLUN) YD%BETAMFBC
READ (KLUN) YD%RMOLMASS
READ (KLUN) YD%REFOLD
READ (KLUN) YD%HENRYA
READ (KLUN) YD%HENRYB
END SUBROUTINE


END MODULE
