MODULE LOAD_TLSCAW_MOD

USE INTDYNSL_MOD, ONLY : TLSCAW

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLSCAW
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TLSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLSCAW), INTENT (OUT) :: YD

READ (KLUN) YD%M_WDLO
READ (KLUN) YD%M_WDLAT
READ (KLUN) YD%M_WDVER
READ (KLUN) YD%M_WDLOMAD
READ (KLUN) YD%M_WDLAMAD
READ (KLUN) YD%M_WDVERMAD
READ (KLUN) YD%NDIM
END SUBROUTINE


END MODULE
