MODULE LOAD_TMP_MOD

USE YOMMP, ONLY : TMP

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMP
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMP), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC, LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT, LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL, LNUMPP
READ (KLUN) LNUMPP
IF (LNUMPP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUMPP (IL1(1):IU1(1)))
  READ (KLUN) YD%NUMPP
ENDIF
READ (KLUN) LNPROCM
IF (LNPROCM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPROCM (IL1(1):IU1(1)))
  READ (KLUN) YD%NPROCM
ENDIF
READ (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRMS (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRMS
ENDIF
READ (KLUN) LNALLMS
IF (LNALLMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NALLMS (IL1(1):IU1(1)))
  READ (KLUN) YD%NALLMS
ENDIF
READ (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLS (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLS
ENDIF
READ (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRSV (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRSV
ENDIF
READ (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRSVF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRSVF
ENDIF
READ (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRMF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRMF
ENDIF
READ (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSPSTAF (IL1(1):IU1(1)))
  READ (KLUN) YD%NSPSTAF
ENDIF
READ (KLUN) LNUMLL
IF (LNUMLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUMLL (IL1(1):IU1(1)))
  READ (KLUN) YD%NUMLL
ENDIF
READ (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLL (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLL
ENDIF
READ (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYLEVS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYLEVS
ENDIF
READ (KLUN) LNPSURF
IF (LNPSURF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPSURF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPSURF
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NONL
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRFRSTLAT
ENDIF
READ (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLSTLAT
ENDIF
READ (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NLSTLAT
ENDIF
READ (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NBSETLEV (IL1(1):IU1(1)))
  READ (KLUN) YD%NBSETLEV
ENDIF
READ (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALINDEX (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALINDEX
ENDIF
READ (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALAT
ENDIF
READ (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALPROC (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALPROC
ENDIF
READ (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOCALINDEX (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOCALINDEX
ENDIF
READ (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLATGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLATGPP
ENDIF
READ (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLONGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLONGPP
ENDIF
READ (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LSPLITLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%LSPLITLAT
ENDIF
READ (KLUN) LMYLATS
IF (LMYLATS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYLATS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYLATS
ENDIF
READ (KLUN) YD%NPSP
READ (KLUN) YD%NSPEC2V
READ (KLUN) YD%NSPEC2VF
READ (KLUN) YD%NSPEC2VDDH
READ (KLUN) YD%NSPEC2V_NH
READ (KLUN) YD%NSPEC2V_NHX
READ (KLUN) YD%NBSETSP
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPOSSP (IL1(1):IU1(1)))
  READ (KLUN) YD%NPOSSP
ENDIF
READ (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDIM0G (IL1(1):IU1(1)))
  READ (KLUN) YD%NDIM0G
ENDIF
END SUBROUTINE


END MODULE
