MODULE STACK_MOD

IMPLICIT NONE

TYPE STACK
  REAL*8, POINTER :: ZDATA (:) => NULL ()
  INTEGER*8 :: ISIZE = 0
  INTEGER*8 :: ICURR = 0
END TYPE

INTERFACE ASSIGNMENT(=)
  MODULE PROCEDURE STACK_ASSIGN
END INTERFACE

PRIVATE
PUBLIC :: STACK, ASSIGNMENT(=)

CONTAINS

SUBROUTINE STACK_ASSIGN (YDSTACK1, YDSTACK2)

TYPE (STACK), INTENT (INOUT) :: YDSTACK1
TYPE (STACK), INTENT (IN)    :: YDSTACK2

YDSTACK1%ISIZE = YDSTACK2%ISIZE - YDSTACK2%ICURR
YDSTACK1%ICURR = 0
YDSTACK1%ZDATA => YDSTACK2%ZDATA (YDSTACK2%ICURR+1:)

END SUBROUTINE

END MODULE
