PROGRAM WRAP_LAPINEA

USE LOAD_GEOMETRY_MOD
USE LOAD_SL_STRUCT_MOD
USE LOAD_MODEL_GENERAL_CONF_TYPE_MOD
USE LOAD_MODEL_DYNAMICS_TYPE_MOD

USE COPY_GEOMETRY_MOD
USE COPY_SL_STRUCT_MOD
USE COPY_MODEL_GENERAL_CONF_TYPE_MOD
USE COPY_MODEL_DYNAMICS_TYPE_MOD

USE LOAD_MOD
#ifdef USE_ACC
USE CUDAFOR
#endif
USE OMP_LIB

USE LOAD_YOMCT0_MOD
USE LOAD_YOMDYNA_MOD
USE LOAD_YOMCVER_MOD
USE LOAD_YOMCST_MOD
USE LOAD_YOMMP0_MOD
USE LOAD_YOMLUN_MOD
USE LOAD_YOMJFH_MOD

USE XRD_GETOPTIONS

USE PARKIND1
USE STACK_MOD

IMPLICIT NONE

INTERFACE CPRS
  PROCEDURE CPRSX1, CPRSX2, CPRSX3, CPRSI1, CPRSI3
END INTERFACE

INTERFACE REALO
  PROCEDURE REALOX1, REALOX2, REALOX3, REALOI1, REALOI3
END INTERFACE

TYPE (GEOMETRY)                :: YDGEOMETRY
TYPE (MODEL_GENERAL_CONF_TYPE) :: YDML_GCONF
TYPE (MODEL_DYNAMICS_TYPE)     :: YDML_DYN
TYPE (SL_STRUCT)               :: YDSL

TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PB1     (:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PB2     (:,:,:)
INTEGER (KIND=JPIM), POINTER, CONTIGUOUS :: KVSEPC  (:)
INTEGER (KIND=JPIM), POINTER, CONTIGUOUS :: KVSEPL  (:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PCCO    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PUF     (:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PVF     (:,:,:)
INTEGER (KIND=JPIM), POINTER, CONTIGUOUS :: KL0     (:,:,:,:)
INTEGER (KIND=JPIM), POINTER, CONTIGUOUS :: KLH0    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PLSCAW  (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PRSCAW  (:,:,:,:)
INTEGER (KIND=JPIM), POINTER, CONTIGUOUS :: KL0H    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PLSCAWH (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PRSCAWH (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PSCO    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER, CONTIGUOUS :: PGFLT1  (:,:,:,:)

#include "lapinea.intfb.h"
#include "abor1.intfb.h"

INTEGER (KIND=JPIM), POINTER :: KVSEPC_OUT  (:)
INTEGER (KIND=JPIM), POINTER :: KVSEPL_OUT  (:)
REAL (KIND=JPRB)   , POINTER :: PCCO_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PUF_OUT     (:,:,:)
REAL (KIND=JPRB)   , POINTER :: PVF_OUT     (:,:,:)
INTEGER (KIND=JPIM), POINTER :: KL0_OUT     (:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: KLH0_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PLSCAW_OUT  (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PRSCAW_OUT  (:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: KL0H_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PLSCAWH_OUT (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PRSCAWH_OUT (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PSCO_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PGFLT1_OUT  (:,:,:,:)

INTEGER :: IDUM, ILUN
INTEGER :: NGPBLKS, NPROMA, NFLEVG
INTEGER :: IST,IEND,IBL,JLON


CHARACTER (LEN=64) :: CLFILE, CLCASE
LOGICAL :: LLDIFF
INTEGER :: ICOUNT, NTIMES, ITIME
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()
INTEGER (KIND=8) :: HEAPSIZE
INTEGER (KIND=4) :: HEAPSIZE4
INTEGER (KIND=4) :: ISTAT
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD


CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT = 0
CALL GETOPTION ("--count", ICOUNT)
HEAPSIZE4 = 0
CALL GETOPTION ("--heapsize", HEAPSIZE4)
NTIMES = 1
CALL GETOPTION ("--times", NTIMES)
CALL CHECKOPTIONS ()

#ifdef USE_ACC
IF (HEAPSIZE4 > 0) THEN
HEAPSIZE = HEAPSIZE4*1024_8*1024_8
ISTAT = CUDADEVICESETLIMIT (CUDALIMITMALLOCHEAPSIZE, HEAPSIZE)
ENDIF

CALL CUDAPROFILERSTOP
#endif

ILUN = 77

#define LOADM(x) CALL O (#x); CALL LOAD_##x (ILUN); CLOSE (ILUN); IDUM

LOADM (YOMCT0) = 0
LOADM (YOMDYNA) = 0
LOADM (YOMCVER) = 0
LOADM (YOMCST) = 0
LOADM (YOMMP0) = 0
LOADM (YOMLUN) = 0
LOADM (YOMJFH) = 0

#undef LOADM

#define LOAD(x) CALL O (#x//".IN"); CALL LOAD (ILUN, x); CLOSE (ILUN); IDUM

LOAD (YDGEOMETRY) = 0 
LOAD (YDML_GCONF) = 0
LOAD (YDSL) = 0
LOAD (YDML_DYN) = 0
LOAD (PB1) = 0
LOAD (PB2) = 0
LOAD (KVSEPC) = 0
LOAD (KVSEPL) = 0
LOAD (PCCO) = 0
LOAD (PUF) = 0
LOAD (PVF) = 0
LOAD (KL0) = 0
LOAD (KLH0) = 0
LOAD (PLSCAW) = 0
LOAD (PRSCAW) = 0
LOAD (KL0H) = 0
LOAD (PLSCAWH) = 0
LOAD (PRSCAWH) = 0
LOAD (PSCO) = 0
LOAD (PGFLT1) = 0

!$acc enter data create (YDGEOMETRY) 
CALL COPY (YDGEOMETRY) 
!$acc enter data create (YDML_GCONF) 
CALL COPY (YDML_GCONF)
!$acc enter data create (YDSL) 
CALL COPY (YDSL) 
!$acc enter data create (YDML_DYN) 
CALL COPY (YDML_DYN) 

IF (ICOUNT == 0) ICOUNT = SIZE (KVSEPC)

NGPBLKS = MIN (SIZE (KVSEPC), ICOUNT)
NPROMA = YDGEOMETRY%YRDIM%NPROMA
NFLEVG = YDGEOMETRY%YRDIMV%NFLEVG

#undef LOAD

#ifdef USE_ACC
CALL CUDAPROFILERSTART 
#endif

DO ITIME = 1, NTIMES

  TSD = OMP_GET_WTIME ()

!$acc data &
!$acc & present (YDGEOMETRY, YDML_GCONF, YDSL, YDML_DYN) copyin (PB1, PB2) &
!$acc & copy (KVSEPC, KVSEPL) &
!$acc & copyout (PCCO, PUF, PVF, KL0, KLH0, PLSCAW, PRSCAW, KL0H, PLSCAWH, PRSCAWH, PSCO,PGFLT1)

  TSC = OMP_GET_WTIME ()

  !$acc parallel loop gang private (YLSTACK)
  DO IBL = 1, NGPBLKS

    IST=1
    IEND=NPROMA

    CALL LAPINEA(&
     ! --- INPUT --------------------------------------------------------------
     & YDGEOMETRY,YDML_GCONF,YDML_DYN,IST,IEND,YDSL,IBL,PB1,PB2(:,:,IBL),&
     ! --- INPUT/OUTPUT -------------------------------------------------------
     & KVSEPC(IBL),KVSEPL(IBL),&
     ! --- OUTPUT -------------------------------------------------------------
     & PCCO(:,:,:,IBL),PUF(:,:,IBL),PVF(:,:,IBL),&
     & KL0(:,:,:,IBL),KLH0(:,:,:,IBL),PLSCAW(:,:,:,IBL),PRSCAW(:,:,:,IBL),&
     & KL0H(:,:,:,IBL),PLSCAWH(:,:,:,IBL),PRSCAWH(:,:,:,IBL),&
     & PSCO(:,:,:,IBL),PGFLT1(:,:,:,IBL),YLSTACK)

  ENDDO
  !$acc end parallel loop

  TEC = OMP_GET_WTIME ()

!$acc end data

  TED = OMP_GET_WTIME ()

  ZTC = ZTC + (TEC - TSC)
  ZTD = ZTD + (TED - TSD)

ENDDO

PRINT *, " ZTD = ", ZTD, ZTD / REAL (NGPBLKS * NPROMA, JPRB)
PRINT *, " ZTC = ", ZTC, ZTC / REAL (NGPBLKS * NPROMA, JPRB)


#ifdef USE_ACC
CALL CUDAPROFILERSTOP
#endif

IF (LLDIFF) THEN

#define LOAD(x) CALL O (#x//".OUT"); CALL LOAD (ILUN, x##_OUT); CLOSE (ILUN); IDUM

LOAD (KVSEPC) = 0
LOAD (KVSEPL) = 0
LOAD (PCCO) = 0
LOAD (PUF) = 0
LOAD (PVF) = 0
LOAD (KL0) = 0
LOAD (KLH0) = 0
LOAD (PLSCAW) = 0
LOAD (PRSCAW) = 0
LOAD (KL0H) = 0
LOAD (PLSCAWH) = 0
LOAD (PRSCAWH) = 0
LOAD (PSCO) = 0
LOAD (PGFLT1) = 0

PRINT *, " DIFF "

DO IBL = 1, NGPBLKS

  IF (ASSOCIATED (IDIFFBLOCK)) THEN
    IF (ALL (IDIFFBLOCK /= IBL)) CYCLE
  ENDIF

  PRINT *, " IBLOCK = ", IBL

  CALL DIFF ("KVSEPC", KVSEPC_OUT (IBL), KVSEPC (IBL))
  CALL DIFF ("KVSEPL", KVSEPL_OUT (IBL), KVSEPL (IBL))
  CALL DIFF ("PCCO", PCCO_OUT (:,:,:,IBL), PCCO (:,:,:,IBL))
ENDDO


ENDIF


CONTAINS

SUBROUTINE O (CDFILE)

INTEGER, PARAMETER :: MYPROC = 1

CHARACTER (LEN=*) :: CDFILE

WRITE (CLFILE, '(I3.3)') MYPROC
CLFILE=TRIM (CDFILE)//"."//TRIM (CLFILE)

OPEN (ILUN, FILE=TRIM (CLCASE)//"/"//TRIM (CLFILE), FORM='UNFORMATTED')

END SUBROUTINE

END



