MODULE COPY_TTNH_MOD

USE YOMTNH, ONLY : TTNH

INTERFACE COPY
MODULE PROCEDURE COPY_TTNH
END INTERFACE

CONTAINS

SUBROUTINE COPY_TTNH (YD)

IMPLICIT NONE
TYPE (TTNH), INTENT (IN) :: YD

!$acc update device (YD%NLENNH95B)

!$acc enter data create (YD%TRAJNH)
!$acc update device (YD%TRAJNH)
!$acc enter data attach (YD%TRAJNH)

END SUBROUTINE

END MODULE
