MODULE COPY_TVERTICAL_GEOM_MOD

USE YOMVERT, ONLY : TVERTICAL_GEOM

INTERFACE COPY
MODULE PROCEDURE COPY_TVERTICAL_GEOM
END INTERFACE

CONTAINS

SUBROUTINE COPY_TVERTICAL_GEOM (YD)
USE COPY_TVAB_MOD
USE COPY_TVETA_MOD
USE COPY_TVFE_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN) :: YD

CALL COPY (YD%YRVAB)

CALL COPY (YD%YRVETA)

CALL COPY (YD%YRVFE)

END SUBROUTINE

END MODULE
