MODULE COPY_TYPE_AERO_WVL_DIAG_MOD

USE YOE_AERODIAG, ONLY : TYPE_AERO_WVL_DIAG

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_AERO_WVL_DIAG
END INTERFACE

CONTAINS

SUBROUTINE COPY_TYPE_AERO_WVL_DIAG (YD)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), INTENT (IN) :: YD

!$acc update device (YD%IWVL)

!$acc update device (YD%IGRIBDIAG)

END SUBROUTINE

END MODULE
