MODULE COPY_TSPNG_MOD

USE SPNG_MOD, ONLY : TSPNG

INTERFACE COPY
MODULE PROCEDURE COPY_TSPNG
END INTERFACE

CONTAINS

SUBROUTINE COPY_TSPNG (YD)

IMPLICIT NONE
TYPE (TSPNG), INTENT (IN) :: YD

!$acc update device (YD%LNSPONGE)

!$acc enter data create (YD%RSPONGF)
!$acc update device (YD%RSPONGF)
!$acc enter data attach (YD%RSPONGF)

END SUBROUTINE

END MODULE
