INTERFACE
!$acc routine(LASCAW_CLO) seq
SUBROUTINE LASCAW_CLO(KFLEV,&
 & KPROM,KST,KPROF,LDT,PDLO,PDLOMAD,PKAPPA,PKHTURB,PCLO,PCLOMAD,PCLOSLD,KSTPT,KSTSZ,PSTACK)

USE PARKIND1 , ONLY : JPIM     ,JPRB

USE YOMDYNA  , ONLY : SLHDKMIN ,SLHDKMAX ,SLHDEPSH,SLHDKREF
USE YOMDYN   , ONLY : TDYN

INTEGER(KIND=JPIM), INTENT(IN)  :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN)  :: KPROM
INTEGER(KIND=JPIM), INTENT(IN)  :: KST
INTEGER(KIND=JPIM), INTENT(IN)  :: KPROF
LOGICAL           , INTENT(IN)  :: LDT(4)
REAL(KIND=JPRB)   , INTENT(IN)  :: PDLO(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PDLOMAD(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PKAPPA(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PKHTURB(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(OUT) :: PCLO(KPROM,KFLEV,3)
REAL(KIND=JPRB)   , INTENT(OUT) :: PCLOMAD(KPROM,KFLEV,3)
REAL(KIND=JPRB)   , INTENT(OUT) :: PCLOSLD(KPROM,KFLEV,3)

INTEGER(KIND=JPIM), INTENT(IN)  :: KSTSZ
INTEGER(KIND=JPIM), INTENT(IN)  :: KSTPT
REAL   (KIND=JPRB), INTENT(INOUT):: PSTACK (KSTSZ)

END SUBROUTINE LASCAW_CLO

END INTERFACE
