INTERFACE
!$acc routine (LASCAW_VINTW) vector
SUBROUTINE LASCAW_VINTW(LDSLHDHEAT,KPROM,KFLEV,KST,KPROF,&
 & LDCOMADV,LDT_SLHD,&
 & KLEV,PLEV,PDVER,PDVERMAD,PSTDDISW,PKAPPA,PKAPPAT,PVETA,PVCUICO_,PVSLD_,PVSLDW_,&
 & PVINTW,PVINTWMAD,PVINTWSLD,PVINTWSLT, YDSTACK)

USE PARKIND1 , ONLY : JPIM     ,JPRB

USE YOMDYNA  , ONLY : SLHDKMIN ,SLHDKMAX,SLHDKREF
USE YOMDYN   , ONLY : TDYN

USE EINT_MOD , ONLY : JPDUP
USE STACK_MOD

LOGICAL           , INTENT(IN)  :: LDSLHDHEAT
INTEGER(KIND=JPIM), INTENT(IN)  :: KPROM
INTEGER(KIND=JPIM), INTENT(IN)  :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN)  :: KST
INTEGER(KIND=JPIM), INTENT(IN)  :: KPROF
LOGICAL           , INTENT(IN)  :: LDCOMADV
LOGICAL           , INTENT(IN)  :: LDT_SLHD(3)
INTEGER(KIND=JPIM), INTENT(IN)  :: KLEV(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PLEV(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PDVER(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PDVERMAD(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PKAPPA(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PSTDDISW(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PKAPPAT(KPROM,KFLEV)
REAL(KIND=JPRB)   , INTENT(IN)  :: PVETA(0:KFLEV+1)
REAL(KIND=JPRB)   , INTENT(IN)  :: PVCUICO_(JPDUP,4,0:KFLEV-1)
REAL(KIND=JPRB)   , INTENT(IN)  :: PVSLD_(JPDUP,3,0:KFLEV-1)
REAL(KIND=JPRB)   , INTENT(IN)  :: PVSLDW_(JPDUP,3,3,0:KFLEV-1)
REAL(KIND=JPRB)   , INTENT(OUT) :: PVINTW(KPROM,KFLEV,3)
REAL(KIND=JPRB)   , INTENT(OUT) :: PVINTWMAD(KPROM,KFLEV,3)
REAL(KIND=JPRB)   , INTENT(OUT) :: PVINTWSLD(KPROM,KFLEV,3)
REAL(KIND=JPRB)   , INTENT(OUT) :: PVINTWSLT(KPROM,KFLEV,3)
TYPE(STACK) :: YDSTACK, YLSTACK

END SUBROUTINE LASCAW_VINTW

END INTERFACE
