MODULE LOAD_TRSCAW_MOD

USE INTDYNSL_MOD, ONLY : TRSCAW

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRSCAW
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TRSCAW (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRSCAW), INTENT (OUT) :: YD

READ (KLUN) YD%M_WCLO
READ (KLUN) YD%M_WCLA
READ (KLUN) YD%M_WVINTW
READ (KLUN) YD%M_WCLOSLD
READ (KLUN) YD%M_WCLASLD
READ (KLUN) YD%M_WCLOSLT
READ (KLUN) YD%M_WCLASLT
READ (KLUN) YD%M_WVINTWSLD
READ (KLUN) YD%M_WVINTWSLT
READ (KLUN) YD%M_WCLOMAD
READ (KLUN) YD%M_WCLAMAD
READ (KLUN) YD%M_WVINTWMAD
READ (KLUN) YD%M_WVINTWS
READ (KLUN) YD%M_WVDERW
READ (KLUN) YD%M_WHVW
READ (KLUN) YD%NDIM
END SUBROUTINE


END MODULE
