MODULE LOAD_TVFE_MOD

USE YOMVERT, ONLY : TVFE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVFE
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVFE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVFE), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LRDDERBF01, LRDDERBF01_IMPL, LRDDERBF10_IMPL, LRDDERBF11, LRDDERBF11_IMPL, LRDDERI, LRDERB, LRDERBF00, LRDERBF01, LRDERBF01_IMPL, LRDERBF10, LRDERBF10_IMPL, LRDERBF11, LRDERBF11_IMPL, LRDERBH00, LRDERBH01, LRDERBH01_IMPL, LRDERGW, LRDERI, LRINTBF00, LRINTBF11, LRINTBF11_IMPL, LRINTE, LRINTGW, LVFE_KNOT
READ (KLUN) LVFE_KNOT
IF (LVFE_KNOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_KNOT (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_KNOT
ENDIF
READ (KLUN) LRINTE
IF (LRINTE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTE
ENDIF
READ (KLUN) LRINTBF00
IF (LRINTBF00) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTBF00 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTBF00
ENDIF
READ (KLUN) LRINTBF11
IF (LRINTBF11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTBF11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTBF11
ENDIF
READ (KLUN) LRDERI
IF (LRDERI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERI
ENDIF
READ (KLUN) LRDERB
IF (LRDERB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERB (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERB
ENDIF
READ (KLUN) LRDERBF00
IF (LRDERBF00) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF00 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF00
ENDIF
READ (KLUN) LRDERBF01
IF (LRDERBF01) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF01 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF01
ENDIF
READ (KLUN) LRDERBF10
IF (LRDERBF10) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF10 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF10
ENDIF
READ (KLUN) LRDERBF11
IF (LRDERBF11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF11
ENDIF
READ (KLUN) LRDERBH00
IF (LRDERBH00) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBH00 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBH00
ENDIF
READ (KLUN) LRDERBH01
IF (LRDERBH01) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBH01 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBH01
ENDIF
READ (KLUN) LRDDERI
IF (LRDDERI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERI
ENDIF
READ (KLUN) LRDDERBF01
IF (LRDDERBF01) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERBF01 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERBF01
ENDIF
READ (KLUN) LRDDERBF11
IF (LRDDERBF11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERBF11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERBF11
ENDIF
READ (KLUN) LRINTBF11_IMPL
IF (LRINTBF11_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTBF11_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTBF11_IMPL
ENDIF
READ (KLUN) LRDERBF01_IMPL
IF (LRDERBF01_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF01_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF01_IMPL
ENDIF
READ (KLUN) LRDERBF10_IMPL
IF (LRDERBF10_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF10_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF10_IMPL
ENDIF
READ (KLUN) LRDERBF11_IMPL
IF (LRDERBF11_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBF11_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBF11_IMPL
ENDIF
READ (KLUN) LRDERBH01_IMPL
IF (LRDERBH01_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERBH01_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERBH01_IMPL
ENDIF
READ (KLUN) LRDDERBF01_IMPL
IF (LRDDERBF01_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERBF01_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERBF01_IMPL
ENDIF
READ (KLUN) LRDDERBF10_IMPL
IF (LRDDERBF10_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERBF10_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERBF10_IMPL
ENDIF
READ (KLUN) LRDDERBF11_IMPL
IF (LRDDERBF11_IMPL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDDERBF11_IMPL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDDERBF11_IMPL
ENDIF
READ (KLUN) LRINTGW
IF (LRINTGW) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RINTGW (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RINTGW
ENDIF
READ (KLUN) LRDERGW
IF (LRDERGW) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDERGW (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDERGW
ENDIF
END SUBROUTINE


END MODULE
