MODULE LOAD_YOMCT0_MOD

USE YOMCT0

CONTAINS

SUBROUTINE LOAD_YOMCT0 (KLUN)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) NCONF
READ (KLUN) NFPOS
READ (KLUN) LR3D
READ (KLUN) LR2D
READ (KLUN) LRSHW
READ (KLUN) LRVEQ
READ (KLUN) NOPT_MEMORY
READ (KLUN) LALLOPR
READ (KLUN) LFDBOP
READ (KLUN) LECFPOS
READ (KLUN) LGRBOP
READ (KLUN) LFBDAP
READ (KLUN) LARPEGEF
READ (KLUN) LARPEGEF_TRAJHR
READ (KLUN) LARPEGEF_TRAJBG
READ (KLUN) LARPEGEF_RDGP_INIT
READ (KLUN) LARPEGEF_RDGP_TRAJHR
READ (KLUN) LARPEGEF_RDGP_TRAJBG
READ (KLUN) CNDISPP
READ (KLUN) CFPNCF
READ (KLUN) CFDIRLST
READ (KLUN) CNPPATH
READ (KLUN) CSCRIPT_PPSERVER
READ (KLUN) CSCRIPT_LAMRTC
READ (KLUN) LNF
READ (KLUN) LSMSSIG
READ (KLUN) CEVENT
READ (KLUN) CMETER
READ (KLUN) LOPDIS
READ (KLUN) NCYCLE
READ (KLUN) CNMEXP
READ (KLUN) CFCLASS
READ (KLUN) CTYPE
READ (KLUN) LBACKG
READ (KLUN) LSPBSBAL
READ (KLUN) LMINIM
READ (KLUN) LIOLEVG
READ (KLUN) NUNDEFLD
READ (KLUN) LREFOUT
READ (KLUN) LREFGEN
READ (KLUN) LSLAG
READ (KLUN) LTWOTL
READ (KLUN) LREGETA
READ (KLUN) LVFE_REGETA
READ (KLUN) NQUAD
READ (KLUN) LNHEE
READ (KLUN) LNHQE
READ (KLUN) LNHDYN
READ (KLUN) N2DINI
READ (KLUN) N3DINI
READ (KLUN) LSPRT
READ (KLUN) NSPPR
READ (KLUN) NFRPOS
READ (KLUN) NFRCORM
READ (KLUN) NFRCO
READ (KLUN) NFRHIS
READ (KLUN) NFRSFXHIS
READ (KLUN) NFRMASSCON
READ (KLUN) NFRGDI
READ (KLUN) NFRSDI
READ (KLUN) NFRDHFG
READ (KLUN) NFRDHFZ
READ (KLUN) NFRDHFD
READ (KLUN) NFRDHP
READ (KLUN) N6BINS
READ (KLUN) NPOSTS
READ (KLUN) NPOSTSMIN
READ (KLUN) NHISTS
READ (KLUN) NHISTSMIN
READ (KLUN) NSFXHISTS
READ (KLUN) NSFXHISTSMIN
READ (KLUN) NMASSCONS
READ (KLUN) NGDITS
READ (KLUN) NSDITS
READ (KLUN) NDHFGTS
READ (KLUN) NDHFZTS
READ (KLUN) NDHFDTS
READ (KLUN) NDHPTS
READ (KLUN) L4DVAR
READ (KLUN) LCANARI
READ (KLUN) NTASKS_CANARI
READ (KLUN) LGUESS
READ (KLUN) LOBS
READ (KLUN) LSIMOB
READ (KLUN) LOBSC1
READ (KLUN) LSCREEN
READ (KLUN) LSCREEN_OPENMP
READ (KLUN) L_SPLIT_SCREEN
READ (KLUN) L_SCREEN_CALL
READ (KLUN) LMONITORING
READ (KLUN) LOBSREF
READ (KLUN) LIFSMIN
READ (KLUN) LIFSTRAJ
READ (KLUN) NCNTVAR
READ (KLUN) LOLDPP
READ (KLUN) NSTEPINI
READ (KLUN) NINTERPTRAJ
READ (KLUN) NINTERPINCR
READ (KLUN) LINFLAT
READ (KLUN) LINFLP9
READ (KLUN) LINFLF1
READ (KLUN) L_OOPS
READ (KLUN) LECMWF
READ (KLUN) LELAM
READ (KLUN) LRPLANE
READ (KLUN) LAROME
READ (KLUN) LCALLSFX
READ (KLUN) LSFXLSM
READ (KLUN) LSFCFLX
READ (KLUN) REXTSHF
READ (KLUN) REXTLHF
READ (KLUN) LROUGH
READ (KLUN) REXTZ0M
READ (KLUN) REXTZ0H
READ (KLUN) LCOUPLO4
READ (KLUN) LCOUPLO4_ENV
READ (KLUN) LSFORC
READ (KLUN) LSFORCS
READ (KLUN) LWRSPECA_GP
READ (KLUN) LSUSPECA_GP
READ (KLUN) LWRSPECA_GP_UV
READ (KLUN) LSUSPECA_GP_UV
READ (KLUN) LGRIB_API
END SUBROUTINE


END MODULE
