MODULE LOAD_TVETA_MOD

USE YOMVERT, ONLY : TVETA

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVETA
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVETA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVETA), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LVETAF, LVETAH, LVFE_ETAF, LVFE_ETAH, LVFE_RDETAH
READ (KLUN) LVETAH
IF (LVETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VETAH
ENDIF
READ (KLUN) LVFE_ETAH
IF (LVFE_ETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_ETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_ETAH
ENDIF
READ (KLUN) LVETAF
IF (LVETAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VETAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VETAF
ENDIF
READ (KLUN) LVFE_ETAF
IF (LVFE_ETAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_ETAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_ETAF
ENDIF
READ (KLUN) LVFE_RDETAH
IF (LVFE_RDETAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VFE_RDETAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VFE_RDETAH
ENDIF
END SUBROUTINE


END MODULE
