MODULE LOAD_TVSPLIP_MOD

USE YOMVSPLIP, ONLY : TVSPLIP

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVSPLIP
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVSPLIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSPLIP), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LRFVV, LRVSPC, LRVSPTRI
READ (KLUN) LRVSPTRI
IF (LRVSPTRI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RVSPTRI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RVSPTRI
ENDIF
READ (KLUN) LRVSPC
IF (LRVSPC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RVSPC (IL1(1):IU1(1)))
  READ (KLUN) YD%RVSPC
ENDIF
READ (KLUN) LRFVV
IF (LRFVV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RFVV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RFVV
ENDIF
END SUBROUTINE


END MODULE
