MODULE LOAD_TDIMV_MOD

USE YOMDIMV, ONLY : TDIMV

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIMV
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TDIMV (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIMV), INTENT (OUT) :: YD

READ (KLUN) YD%NFLEVG
READ (KLUN) YD%NFLEVL
READ (KLUN) YD%NFLEVLMX
READ (KLUN) YD%NFLSUR
READ (KLUN) YD%NFLSUL
READ (KLUN) YD%NFLSA
READ (KLUN) YD%NFLEN
READ (KLUN) YD%NIOLEVG
END SUBROUTINE


END MODULE
