MODULE LOAD_TPTRSLB2_MOD

USE PTRSLB2, ONLY : TPTRSLB2

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPTRSLB2
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPTRSLB2 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPTRSLB2), INTENT (OUT) :: YD

READ (KLUN) YD%NFLDSLB2
READ (KLUN) YD%MSLBUF2
READ (KLUN) YD%MSLB2DBBC1
READ (KLUN) YD%MSLB2DPHI1
READ (KLUN) YD%MSLB2USI
READ (KLUN) YD%MSLB2VSI
READ (KLUN) YD%MSLB2TSI
READ (KLUN) YD%MSLB2PDSI
READ (KLUN) YD%MSLB2VDSI
READ (KLUN) YD%MSLB2SPSI
READ (KLUN) YD%MSLB2VVEL
READ (KLUN) YD%MSLB2URL
READ (KLUN) YD%MSLB2VRL
READ (KLUN) YD%MSLB2WRL
READ (KLUN) YD%MSLB2URL5
READ (KLUN) YD%MSLB2VRL5
READ (KLUN) YD%MSLB2WRL5
READ (KLUN) YD%MSLB2USI5
READ (KLUN) YD%MSLB2VSI5
READ (KLUN) YD%MSLB2U15
READ (KLUN) YD%MSLB2V15
READ (KLUN) YD%MSLB2T15
READ (KLUN) YD%MSLB2Q15
READ (KLUN) YD%MSLB2KAPPA
READ (KLUN) YD%MSLB2KAPPAT
READ (KLUN) YD%MSLB2KAPPAM
READ (KLUN) YD%MSLB2KAPPAH
READ (KLUN) YD%MSLB2KAPPA5
READ (KLUN) YD%MSLB2KAPPAT5
READ (KLUN) YD%MSLB2GWF
READ (KLUN) YD%MSLB2GDW
READ (KLUN) YD%MSLB2GWS
READ (KLUN) YD%MSLB2STDDISU
READ (KLUN) YD%MSLB2STDDISV
READ (KLUN) YD%MSLB2STDDISW
END SUBROUTINE


END MODULE
