MODULE LOAD_TLEP_MOD

USE YEMLAP, ONLY : TLEP

INTERFACE LOAD
MODULE PROCEDURE LOAD_TLEP
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TLEP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TLEP), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO, LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
READ (KLUN) LNCPL2M
IF (LNCPL2M) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL2M (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL2M
ENDIF
READ (KLUN) LNCPL4M
IF (LNCPL4M) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL4M (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL4M
ENDIF
READ (KLUN) LNCPLM
IF (LNCPLM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPLM (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPLM
ENDIF
READ (KLUN) LNCPL2N
IF (LNCPL2N) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL2N (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL2N
ENDIF
READ (KLUN) LNCPL4N
IF (LNCPL4N) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPL4N (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPL4N
ENDIF
READ (KLUN) LNCPLN
IF (LNCPLN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NCPLN (IL1(1):IU1(1)))
  READ (KLUN) YD%NCPLN
ENDIF
READ (KLUN) LRLEPDIN
IF (LRLEPDIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPDIN (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPDIN
ENDIF
READ (KLUN) LRLEPINN
IF (LRLEPINN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPINN (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPINN
ENDIF
READ (KLUN) LRLEPDIM
IF (LRLEPDIM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPDIM (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPDIM
ENDIF
READ (KLUN) LRLEPINM
IF (LRLEPINM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLEPINM (IL1(1):IU1(1)))
  READ (KLUN) YD%RLEPINM
ENDIF
READ (KLUN) LNESM0
IF (LNESM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NESM0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NESM0
ENDIF
READ (KLUN) LNESPZERO
IF (LNESPZERO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NESPZERO (IL1(1):IU1(1)))
  READ (KLUN) YD%NESPZERO
ENDIF
READ (KLUN) LNESM0G
IF (LNESM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NESM0G (IL1(1):IU1(1)))
  READ (KLUN) YD%NESM0G
ENDIF
READ (KLUN) LNPME
IF (LNPME) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPME (IL1(1):IU1(1)))
  READ (KLUN) YD%NPME
ENDIF
READ (KLUN) LNPNE
IF (LNPNE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPNE (IL1(1):IU1(1)))
  READ (KLUN) YD%NPNE
ENDIF
READ (KLUN) LMVALUE
IF (LMVALUE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MVALUE (IL1(1):IU1(1)))
  READ (KLUN) YD%MVALUE
ENDIF
END SUBROUTINE


END MODULE
