MODULE LOAD_TELBC_GEO_MOD

USE YEMLBC_GEO, ONLY : TELBC_GEO

INTERFACE LOAD
MODULE PROCEDURE LOAD_TELBC_GEO
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TELBC_GEO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TELBC_GEO), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LNIND_LEN, LNIND_LIST
READ (KLUN) YD%NEDLST
READ (KLUN) LNIND_LIST
IF (LNIND_LIST) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NIND_LIST (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NIND_LIST
ENDIF
READ (KLUN) LNIND_LEN
IF (LNIND_LEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NIND_LEN (IL1(1):IU1(1)))
  READ (KLUN) YD%NIND_LEN
ENDIF
END SUBROUTINE


END MODULE
