MODULE LOAD_YOMDYNA_MOD

USE YOMDYNA

CONTAINS

SUBROUTINE LOAD_YOMDYNA (KLUN)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) NPDVAR
READ (KLUN) NVDVAR
READ (KLUN) ND4SYS
READ (KLUN) LNHX
READ (KLUN) LNHXDER
READ (KLUN) LGWADV
READ (KLUN) NGWADVSI
READ (KLUN) LRDBBC
READ (KLUN) LSI_NHEE
READ (KLUN) LNHQE_C2
READ (KLUN) LNHQE_SIHYD
READ (KLUN) LNHEE_SVDLAPL_FIRST
READ (KLUN) LSLHD
READ (KLUN) LSLHD_W
READ (KLUN) LSLHD_T
READ (KLUN) LSLHD_SPD
READ (KLUN) LSLHD_SVD
READ (KLUN) LSLHD_GFL
READ (KLUN) LSLHD_OLD
READ (KLUN) LSLHD_STATIC
READ (KLUN) LSLHDQUAD
READ (KLUN) LSLHDVER
READ (KLUN) SLHDKMIN
READ (KLUN) SLHDKMAX
READ (KLUN) SLHDKREF
READ (KLUN) SLHDEPSH
READ (KLUN) SLHDEPSV
READ (KLUN) LGRADSP
READ (KLUN) LGRADGP
READ (KLUN) L3DTURB
READ (KLUN) LSLDIA
READ (KLUN) LRPRSLTRJ
READ (KLUN) LRALTVDISP
READ (KLUN) LVSPLIP
READ (KLUN) LCOMAD
READ (KLUN) LCOMADH
READ (KLUN) LCOMADV
READ (KLUN) LCOMAD_W
READ (KLUN) LCOMAD_T
READ (KLUN) LCOMAD_SPD
READ (KLUN) LCOMAD_SVD
READ (KLUN) LCOMAD_SP
READ (KLUN) LCOMAD_GFL
READ (KLUN) LNESCT
READ (KLUN) LNESCV
READ (KLUN) LNESC
READ (KLUN) LSETTLST
READ (KLUN) LSETTLSV
READ (KLUN) LSETTLS
READ (KLUN) LELTRA
READ (KLUN) LSLINLC2
READ (KLUN) LSLINL
READ (KLUN) LAPRXPK
READ (KLUN) NDLNPR
READ (KLUN) RHYDR0
READ (KLUN) LRUBC
READ (KLUN) LPC_FULL
READ (KLUN) LPC_CHEAP
READ (KLUN) LPC_CHEAP2
READ (KLUN) LMIXETTLS
READ (KLUN) LMIXETTLS_PRINT
READ (KLUN) RMIXNL_TRH
READ (KLUN) LDRY_ECMWF
READ (KLUN) L_RDRY_VD
END SUBROUTINE


END MODULE
