MODULE LOAD_YOMCVER_MOD

USE YOMCVER

CONTAINS

SUBROUTINE LOAD_YOMCVER (KLUN)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) NVSCH
READ (KLUN) NVFE_TYPE
READ (KLUN) NVFE_ORDER
READ (KLUN) NVFE_INTBC
READ (KLUN) NVFE_DERBC
READ (KLUN) NVFE_INTERNALS
READ (KLUN) NVFE_BC
READ (KLUN) LVERTFE
READ (KLUN) LVFE_LAPL
READ (KLUN) LVFE_LAPL_BC
READ (KLUN) LVFE_LAPL_TBC
READ (KLUN) LVFE_LAPL_BBC
READ (KLUN) LVFE_LAPL2PI
READ (KLUN) RLAPL2PI
READ (KLUN) LVFE_X_TERM
READ (KLUN) LVFE_Z_TERM
READ (KLUN) LVFE_GW
READ (KLUN) LVFE_DELNHPRE
READ (KLUN) LVFE_GWMPA
READ (KLUN) LVFE_CENTRI
READ (KLUN) RVFE_CENTRI
READ (KLUN) LVFE_APPROX
READ (KLUN) LVFE_ECMWF
READ (KLUN) LVFE_LAPL_HALF
READ (KLUN) LVFE_FIX_ORDER
READ (KLUN) LVFE_GW_HALF
READ (KLUN) LVFE_MAXIMAS
READ (KLUN) LVFE_VERBOSE
READ (KLUN) RMINDETA
END SUBROUTINE


END MODULE
