MODULE LOAD_TYPE_GFL_COMP_MOD

USE YOM_YGFL, ONLY : TYPE_GFL_COMP

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_GFL_COMP
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TYPE_GFL_COMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFL_COMP), INTENT (OUT) :: YD

READ (KLUN) YD%CNAME
READ (KLUN) YD%IGRBCODE
READ (KLUN) YD%LADV
READ (KLUN) YD%LADV5
READ (KLUN) YD%LTDIABLIN
READ (KLUN) YD%LHORTURB
READ (KLUN) YD%NREQIN
READ (KLUN) YD%LREQOUT
READ (KLUN) YD%LGPINGP
READ (KLUN) YD%LGP
READ (KLUN) YD%LSP
READ (KLUN) YD%LCDERS
READ (KLUN) YD%LACTIVE
READ (KLUN) YD%LTHERMACT
READ (KLUN) YD%R
READ (KLUN) YD%RCP
READ (KLUN) YD%LT9
READ (KLUN) YD%LT1
READ (KLUN) YD%LT5
READ (KLUN) YD%LPHY
READ (KLUN) YD%LPT
READ (KLUN) YD%LTRAJIO
READ (KLUN) YD%LDIAG
READ (KLUN) YD%LPC
READ (KLUN) YD%REFVALI
READ (KLUN) YD%LADJUST0
READ (KLUN) YD%LADJUST1
READ (KLUN) YD%NCOUPLING
READ (KLUN) YD%REFVALC
READ (KLUN) YD%LBIPER
READ (KLUN) YD%CSLINT
READ (KLUN) YD%MP
READ (KLUN) YD%MPL
READ (KLUN) YD%MPM
READ (KLUN) YD%MP9
READ (KLUN) YD%MP9_PH
READ (KLUN) YD%MP1
READ (KLUN) YD%MP5
READ (KLUN) YD%MP5L
READ (KLUN) YD%MP5M
READ (KLUN) YD%MPSLP
READ (KLUN) YD%MPSP
READ (KLUN) YD%MP_SPL
READ (KLUN) YD%MP_SL1
READ (KLUN) YD%MP_SLX
READ (KLUN) YD%MPPT
READ (KLUN) YD%MPPC
READ (KLUN) YD%LWATER
READ (KLUN) YD%LPRECIP
READ (KLUN) YD%RLZER
READ (KLUN) YD%NCOUPLO4
READ (KLUN) YD%LASSIM
READ (KLUN) YD%IGRIBDV
READ (KLUN) YD%IGRIBTC
READ (KLUN) YD%IGRIBSFC
READ (KLUN) YD%IGRIBDIAG
READ (KLUN) YD%LDIFF
READ (KLUN) YD%LCONV
READ (KLUN) YD%RMOLMASS
READ (KLUN) YD%REFOLD
READ (KLUN) YD%HENRYA
READ (KLUN) YD%HENRYB
READ (KLUN) YD%LNEGFIX
READ (KLUN) YD%LCOMAD
READ (KLUN) YD%LMASSFIX
READ (KLUN) YD%BETAMFBC
READ (KLUN) YD%IFID
NULLIFY (YD%PREVIOUS)
END SUBROUTINE


END MODULE
