MODULE LOAD_TSPGEOM_MOD

USE TYPE_SPGEOM, ONLY : TSPGEOM

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSPGEOM
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TSPGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSPGEOM), INTENT (OUT) :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LGMR, LSCGMAP
READ (KLUN) LGMR
IF (LGMR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GMR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%GMR
ENDIF
READ (KLUN) LSCGMAP
IF (LSCGMAP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SCGMAP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SCGMAP
ENDIF
READ (KLUN) YD%ESCGMAP
END SUBROUTINE


END MODULE
