MODULE LOAD_TPTRGPPC_MOD

USE PTRGPPC, ONLY : TPTRGPPC

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPTRGPPC
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPTRGPPC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPTRGPPC), INTENT (OUT) :: YD

READ (KLUN) YD%NFGPPC
READ (KLUN) YD%MGPPC
READ (KLUN) YD%MGPPCF_U
READ (KLUN) YD%MGPPCF_V
READ (KLUN) YD%MGPPCF_T
READ (KLUN) YD%MGPPCF_SPD
READ (KLUN) YD%MGPPCF_SVD
READ (KLUN) YD%MGPPCF_SP
READ (KLUN) YD%MGPPCF_CP
READ (KLUN) YD%MGPPCF_NHX
READ (KLUN) YD%MGPPCF_UP
READ (KLUN) YD%MGPPCF_VP
READ (KLUN) YD%MGPPCF_TP
READ (KLUN) YD%MGPPCF_GFLP
READ (KLUN) YD%MGPPCF_BBC
READ (KLUN) YD%MGPPC5
READ (KLUN) YD%MGPPCF_U5
READ (KLUN) YD%MGPPCF_V5
READ (KLUN) YD%MGPPCF_T5
READ (KLUN) YD%MGPPCF_SPD5
READ (KLUN) YD%MGPPCF_SVD5
READ (KLUN) YD%MGPPCF_SP5
END SUBROUTINE


END MODULE
