MODULE LOAD_GEOMETRY_MOD

USE TYPE_GEOMETRY, ONLY : GEOMETRY

INTERFACE LOAD
MODULE PROCEDURE LOAD_GEOMETRY
END INTERFACE

CONTAINS

SUBROUTINE LOAD_GEOMETRY (KLUN, YD)
USE LOAD_TCSGEOM_MOD
USE LOAD_TCSGLEG_MOD
USE LOAD_TDIM_MOD
USE LOAD_TDIMV_MOD
USE LOAD_TEDIM_MOD
USE LOAD_TEGEO_MOD
USE LOAD_TEGSL_MOD
USE LOAD_TELBC_GEO_MOD
USE LOAD_TEMMP_MOD
USE LOAD_TGEM_MOD
USE LOAD_TGSGEOM_MOD
USE LOAD_THSLMER_MOD
USE LOAD_TLAP_MOD
USE LOAD_TLEP_MOD
USE LOAD_TMP_MOD
USE LOAD_TOROG_MOD
USE LOAD_TSPGEOM_MOD
USE LOAD_TSTA_MOD
USE LOAD_TVAB_MOD
USE LOAD_TVERTICAL_GEOM_MOD
USE LOAD_TVETA_MOD
USE LOAD_TVFE_MOD
USE LOAD_TVSLETA_MOD
USE LOAD_TVSPLIP_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY), INTENT (OUT) :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYRCSGEOM, LYRCSGEOMAD, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA, LYRVFE
CALL LOAD (KLUN, YD%YRVERT_GEOM)
READ (KLUN) LYRVAB
IF (LYRVAB) THEN
  ALLOCATE (YD%YRVAB)
  CALL LOAD (KLUN, YD%YRVAB)
ELSE
  NULLIFY (YD%YRVAB)
ENDIF
READ (KLUN) LYRVETA
IF (LYRVETA) THEN
  ALLOCATE (YD%YRVETA)
  CALL LOAD (KLUN, YD%YRVETA)
ELSE
  NULLIFY (YD%YRVETA)
ENDIF
READ (KLUN) LYRVFE
IF (LYRVFE) THEN
  ALLOCATE (YD%YRVFE)
  CALL LOAD (KLUN, YD%YRVFE)
ELSE
  NULLIFY (YD%YRVFE)
ENDIF
CALL LOAD (KLUN, YD%YRSTA)
CALL LOAD (KLUN, YD%YRLAP)
CALL LOAD (KLUN, YD%YRCSGLEG)
CALL LOAD (KLUN, YD%YRDIM)
CALL LOAD (KLUN, YD%YRDIMV)
CALL LOAD (KLUN, YD%YRMP)
CALL LOAD (KLUN, YD%YRGEM)
CALL LOAD (KLUN, YD%YRVSPLIP)
CALL LOAD (KLUN, YD%YRVSLETA)
CALL LOAD (KLUN, YD%YRHSLMER)
READ (KLUN) LYRCSGEOM
IF (LYRCSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL LOAD (KLUN, YD%YRCSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRCSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRCSGEOM_NB)
READ (KLUN) LYRGSGEOM
IF (LYRGSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRGSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL LOAD (KLUN, YD%YRGSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRGSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRGSGEOM_NB)
READ (KLUN) LYRCSGEOMAD
IF (LYRCSGEOMAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCSGEOMAD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL LOAD (KLUN, YD%YRCSGEOMAD (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRCSGEOMAD)
ENDIF
CALL LOAD (KLUN, YD%YRCSGEOMAD_NB)
READ (KLUN) LYRGSGEOMAD
IF (LYRGSGEOMAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRGSGEOMAD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL LOAD (KLUN, YD%YRGSGEOMAD (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRGSGEOMAD)
ENDIF
CALL LOAD (KLUN, YD%YRGSGEOMAD_NB)
READ (KLUN) LYROROG
IF (LYROROG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YROROG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL LOAD (KLUN, YD%YROROG (J1))
  ENDDO
ENDIF
CALL LOAD (KLUN, YD%YSPGEOM)
CALL LOAD (KLUN, YD%YVABIO)
CALL LOAD (KLUN, YD%YREDIM)
CALL LOAD (KLUN, YD%YREGEO)
CALL LOAD (KLUN, YD%YREMP)
CALL LOAD (KLUN, YD%YRELAP)
CALL LOAD (KLUN, YD%YREGSL)
READ (KLUN) LYRELBC_GEO
IF (LYRELBC_GEO) THEN
  ALLOCATE (YD%YRELBC_GEO)
  CALL LOAD (KLUN, YD%YRELBC_GEO)
ELSE
  NULLIFY (YD%YRELBC_GEO)
ENDIF
END SUBROUTINE


END MODULE
