MODULE LOAD_YOMCST_MOD

USE YOMCST

CONTAINS

SUBROUTINE LOAD_YOMCST (KLUN)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) RPI
READ (KLUN) RCLUM
READ (KLUN) RHPLA
READ (KLUN) RKBOL
READ (KLUN) RNAVO
READ (KLUN) RDAY
READ (KLUN) RDAYI
READ (KLUN) RHOUR
READ (KLUN) REA
READ (KLUN) REPSM
READ (KLUN) RSIYEA
READ (KLUN) RSIDAY
READ (KLUN) ROMEGA
READ (KLUN) RA
READ (KLUN) RG
READ (KLUN) R1SA
READ (KLUN) RSIGMA
READ (KLUN) RI0
READ (KLUN) R
READ (KLUN) RMD
READ (KLUN) RMV
READ (KLUN) RMO3
READ (KLUN) RD
READ (KLUN) RV
READ (KLUN) RCPD
READ (KLUN) RCPV
READ (KLUN) RCVD
READ (KLUN) RCVV
READ (KLUN) RKAPPA
READ (KLUN) RETV
READ (KLUN) RMCO2
READ (KLUN) RMCH4
READ (KLUN) RMN2O
READ (KLUN) RMCO
READ (KLUN) RMHCHO
READ (KLUN) RMNO2
READ (KLUN) RMSO2
READ (KLUN) RMSO4
READ (KLUN) RCW
READ (KLUN) RCS
READ (KLUN) RATM
READ (KLUN) RTT
READ (KLUN) RLVTT
READ (KLUN) RLSTT
READ (KLUN) RLVZER
READ (KLUN) RLSZER
READ (KLUN) RLMLT
READ (KLUN) RDT
READ (KLUN) RESTT
READ (KLUN) RGAMW
READ (KLUN) RBETW
READ (KLUN) RALPW
READ (KLUN) RGAMS
READ (KLUN) RBETS
READ (KLUN) RALPS
READ (KLUN) RALPD
READ (KLUN) RBETD
READ (KLUN) RGAMD
READ (KLUN) RSNAN
END SUBROUTINE


END MODULE
