MODULE LOAD_MOD

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

INTERFACE LOAD
MODULE PROCEDURE LOADX0
MODULE PROCEDURE LOADX1
MODULE PROCEDURE LOADX2
MODULE PROCEDURE LOADX3
MODULE PROCEDURE LOADX4
MODULE PROCEDURE LOADX5
MODULE PROCEDURE LOADI0
MODULE PROCEDURE LOADI1
MODULE PROCEDURE LOADI2
MODULE PROCEDURE LOADI3
MODULE PROCEDURE LOADI4
MODULE PROCEDURE LOADL0
MODULE PROCEDURE LOADL3
MODULE PROCEDURE LOADL4
MODULE PROCEDURE LOADC0
MODULE PROCEDURE LOADC1
MODULE PROCEDURE LOADC2
END INTERFACE LOAD

INTERFACE DIFF
MODULE PROCEDURE DIFFX0
MODULE PROCEDURE DIFFX1
MODULE PROCEDURE DIFFX2
MODULE PROCEDURE DIFFX3
MODULE PROCEDURE DIFFX4
MODULE PROCEDURE DIFFX5
MODULE PROCEDURE DIFFI0
MODULE PROCEDURE DIFFL0
MODULE PROCEDURE DIFFI1
MODULE PROCEDURE DIFFL3
MODULE PROCEDURE DIFFL4
MODULE PROCEDURE DIFFC0
MODULE PROCEDURE DIFFC1
MODULE PROCEDURE DIFFC2
END INTERFACE DIFF

INTEGER, PARAMETER :: ILUN_IN = 77, ILUN_OUT = 88, ILUNC = 99

CONTAINS

SUBROUTINE OPEN_LOAD (CDFILE)
CHARACTER (LEN=*) :: CDFILE

OPEN (ILUN_IN, FILE=TRIM (CDFILE)//'.IN', FORM="UNFORMATTED", ACTION="READ")
OPEN (ILUN_OUT, FILE=TRIM (CDFILE)//'.OUT', FORM="UNFORMATTED", ACTION="READ")
END SUBROUTINE OPEN_LOAD

SUBROUTINE CLOSE_LOAD
CLOSE (ILUN_IN)
CLOSE (ILUN_OUT)
END SUBROUTINE CLOSE_LOAD

SUBROUTINE DIFFX0 (CDNAME, X0, X0_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X0, X0_1
IF (X0 /= X0_1) THEN
  WRITE (*, '(A32,12X,3E25.17)') CDNAME, X0, X0_1, X0_1 - X0
ENDIF
END SUBROUTINE DIFFX0

SUBROUTINE LOADX0 (ILUN, X0)
INTEGER          :: ILUN
REAL (KIND=JPRB) :: X0
READ (ILUN) X0
END SUBROUTINE LOADX0

SUBROUTINE DIFFX1 (CDNAME, X1, X1_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X1 (:), X1_1 (:)
INTEGER :: I1
DO I1 = 1, SIZE (X1)
  IF (X1 (I1) /= X1_1 (I1)) THEN
    WRITE (*, '(A32,I12,12X,3E25.17)') CDNAME, I1, X1 (I1), X1_1 (I1), X1_1 (I1) - X1 (I1)
  ENDIF
ENDDO
END SUBROUTINE DIFFX1

SUBROUTINE LOADX1 (ILUN, X1)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X1 (:)
INTEGER :: IL (1), IB (1)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X1 (IL (1): IB (1)))
READ (ILUN) X1
END SUBROUTINE LOADX1

SUBROUTINE DIFFX2 (CDNAME, X2, X2_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X2 (:,:), X2_1 (:,:)
INTEGER :: I1, I2
DO I1 = 1, SIZE (X2, 1)
DO I2 = 1, SIZE (X2, 2)
  IF (X2 (I1, I2) /= X2_1 (I1, I2)) THEN
    WRITE (*, '(A32,I12,I12,3E25.17)') CDNAME, I1, I2, X2 (I1, I2), X2_1 (I1, I2), X2_1 (I1, I2) - X2 (I1, I2)
  ENDIF
ENDDO
ENDDO
END SUBROUTINE DIFFX2

SUBROUTINE DIFFX3 (CDNAME, X3, X3_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X3 (:,:,:), X3_1 (:,:,:)
INTEGER :: I1, I2, I3
DO I1 = 1, SIZE (X3, 1)
DO I2 = 1, SIZE (X3, 2)
DO I3 = 1, SIZE (X3, 3)
  IF (X3 (I1, I2, I3) /= X3_1 (I1, I2, I3)) THEN
    WRITE (*, '(A32,I12,I12,I12,3E25.17)') CDNAME, I1, I2, I3, X3 (I1, I2, I3), X3_1 (I1, I2, I3), &
         & X3_1 (I1, I2, I3) - X3 (I1, I2, I3)
  ENDIF
ENDDO
ENDDO
ENDDO
END SUBROUTINE DIFFX3

SUBROUTINE DIFFX4 (CDNAME, X4, X4_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X4 (:,:,:,:), X4_1 (:,:,:,:)
INTEGER :: I1, I2, I3, I4
DO I1 = 1, SIZE (X4, 1)
DO I2 = 1, SIZE (X4, 2)
DO I3 = 1, SIZE (X4, 3)
DO I4 = 1, SIZE (X4, 4)
  IF (X4 (I1, I2, I3, I4) /= X4_1 (I1, I2, I3, I4)) THEN
    WRITE (*, '(A32,I12,I12,I12,I12,3E25.17)') CDNAME, I1, I2, I3, I4, X4 (I1, I2, I3, I4), X4_1 (I1, I2, I3, I4), &
         & X4_1 (I1, I2, I3, I4) - X4 (I1, I2, I3, I4)
  ENDIF
ENDDO
ENDDO
ENDDO
ENDDO
END SUBROUTINE DIFFX4

SUBROUTINE DIFFX5 (CDNAME, X5, X5_1)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRB) :: X5 (:,:,:,:,:), X5_1 (:,:,:,:,:)
INTEGER :: I1, I2, I3, I4, I5
DO I1 = 1, SIZE (X5, 1)
DO I2 = 1, SIZE (X5, 2)
DO I3 = 1, SIZE (X5, 3)
DO I4 = 1, SIZE (X5, 4)
DO I5 = 1, SIZE (X5, 5)
  IF (X5 (I1, I2, I3, I4, I5) /= X5_1 (I1, I2, I3, I4, I5)) THEN
    WRITE (*, '(A32,I12,I12,I12,I12,I12,3E25.17)') CDNAME, I1, I2, I3, I4, I5, X5 (I1, I2, I3, I4, I5), X5_1 (I1, I2, I3, I4, I5), &
         & X5_1 (I1, I2, I3, I4, I5) - X5 (I1, I2, I3, I4, I5)
  ENDIF
ENDDO
ENDDO
ENDDO
ENDDO
ENDDO
END SUBROUTINE DIFFX5

SUBROUTINE LOADX2 (ILUN, X2)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X2 (:,:)
INTEGER :: IL (2), IB (2)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X2 (IL (1): IB (1), IL (2): IB (2)))
READ (ILUN) X2
END SUBROUTINE LOADX2

SUBROUTINE LOADX3 (ILUN, X3)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X3 (:,:,:)
INTEGER :: IL (3), IB (3)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X3 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3)))
READ (ILUN) X3
END SUBROUTINE LOADX3

SUBROUTINE LOADX4 (ILUN, X4)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X4 (:,:,:,:)
INTEGER :: IL (4), IB (4)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X4 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3), IL (4): IB (4)))
READ (ILUN) X4
END SUBROUTINE LOADX4

SUBROUTINE LOADX5 (ILUN, X5)
INTEGER                   :: ILUN
REAL (KIND=JPRB), POINTER :: X5 (:,:,:,:,:)
INTEGER :: IL (5), IB (5)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (X5 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3), IL (4): IB (4), IL (5): IB (5)))
READ (ILUN) X5
END SUBROUTINE LOADX5

SUBROUTINE DIFFI0 (CDNAME, I0, I0_1)
CHARACTER (LEN=*) :: CDNAME
INTEGER :: I0, I0_1
IF (I0 /= I0_1) THEN
  WRITE (*, '(A32,12X,12X,3I25)') CDNAME, I0, I0_1, I0-I0_1
ENDIF
END SUBROUTINE DIFFI0

SUBROUTINE DIFFI1 (CDNAME, J1, J1_1)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM) :: J1 (:), J1_1 (:)
INTEGER :: I1
DO I1 = 1, SIZE (J1)
  IF (J1 (I1) /= J1_1 (I1)) THEN
    WRITE (*, '(A32,I12,12X,3I25)') CDNAME, I1, J1 (I1), J1_1 (I1), J1_1 (I1) - J1 (I1)
  ENDIF
ENDDO
END SUBROUTINE DIFFI1

SUBROUTINE LOADI0 (ILUN, I0)
INTEGER             :: ILUN
INTEGER (KIND=JPIM) :: I0
READ (ILUN) I0
END SUBROUTINE LOADI0

SUBROUTINE LOADI1 (ILUN, I1)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I1 (:)
INTEGER :: IL (1), IB (1)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I1 (IL (1): IB (1)))
READ (ILUN) I1
END SUBROUTINE LOADI1

SUBROUTINE LOADI2 (ILUN, I2)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I2 (:,:)
INTEGER :: IL (2), IB (2)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I2 (IL (1): IB (1), IL (2): IB (2)))
READ (ILUN) I2
END SUBROUTINE LOADI2

SUBROUTINE LOADI3 (ILUN, I3)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I3 (:,:,:)
INTEGER :: IL (3), IB (3)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I3 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3)))
READ (ILUN) I3
END SUBROUTINE LOADI3

SUBROUTINE LOADI4 (ILUN, I4)
INTEGER                   :: ILUN
INTEGER (KIND=JPIM), POINTER :: I4 (:,:,:,:)
INTEGER :: IL (4), IB (4)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (I4 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3), IL (4): IB (4)))
READ (ILUN) I4
END SUBROUTINE LOADI4

SUBROUTINE DIFFL0 (CDNAME, L0, L0_1)
CHARACTER (LEN=*) :: CDNAME
LOGICAL :: L0, L0_1
IF (.NOT. (L0 .EQV. L0_1)) THEN
  WRITE (*, '(A32,24X,3L25)') CDNAME, L0, L0_1, .FALSE.
ENDIF
END SUBROUTINE DIFFL0

SUBROUTINE DIFFL3 (CDNAME, L3, L3_1)
CHARACTER (LEN=*) :: CDNAME
LOGICAL :: L3 (:,:,:), L3_1 (:,:,:)
INTEGER :: I1, I2, I3
DO I1 = 1, SIZE (L3, 1)
DO I2 = 1, SIZE (L3, 2)
DO I3 = 1, SIZE (L3, 3)
  IF (.NOT. (L3 (I1, I2, I3) .EQV. L3_1 (I1, I2, I3))) THEN
    WRITE (*, '(A32,I12,I12,I12,3L25)') CDNAME, I1, I2, I3, L3 (I1, I2, I3), L3_1 (I1, I2, I3), .FALSE.
  ENDIF
ENDDO
ENDDO
ENDDO
END SUBROUTINE DIFFL3

SUBROUTINE DIFFL4 (CDNAME, L4, L4_1)
CHARACTER (LEN=*) :: CDNAME
LOGICAL :: L4 (:,:,:,:), L4_1 (:,:,:,:)
INTEGER :: I1, I2, I3, I4
DO I1 = 1, SIZE (L4, 1)
DO I2 = 1, SIZE (L4, 2)
DO I3 = 1, SIZE (L4, 3)
DO I4 = 1, SIZE (L4, 4)
  IF (.NOT. (L4 (I1, I2, I3, I4) .EQV. L4_1 (I1, I2, I3, I4))) THEN
    WRITE (*, '(A32,I12,I12,I12,I12,3L25)') CDNAME, I1, I2, I3, I4, L4 (I1, I2, I3, I4), L4_1 (I1, I2, I3, I4), .FALSE.
  ENDIF
ENDDO
ENDDO
ENDDO
ENDDO
END SUBROUTINE DIFFL4

SUBROUTINE LOADL0 (ILUN, L0)
INTEGER :: ILUN
LOGICAL :: L0
READ (ILUN) L0
END SUBROUTINE LOADL0

SUBROUTINE LOADL3 (ILUN, L3)
INTEGER                   :: ILUN
LOGICAL, POINTER :: L3 (:,:,:)
INTEGER :: IL (3), IB (3)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (L3 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3)))
READ (ILUN) L3
END SUBROUTINE LOADL3

SUBROUTINE LOADL4 (ILUN, L4)
INTEGER                   :: ILUN
LOGICAL, POINTER :: L4 (:,:,:,:)
INTEGER :: IL (4), IB (4)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (L4 (IL (1): IB (1), IL (2): IB (2), IL (3): IB (3), IL (4): IB (4)))
READ (ILUN) L4
END SUBROUTINE LOADL4

SUBROUTINE DIFFC0 (CDNAME, C0, C0_1)
CHARACTER (LEN=*) :: CDNAME
CHARACTER (LEN=*) :: C0, C0_1
IF (C0 .NE. C0_1) THEN
  WRITE (*, '(A32,24X,2A25)') CDNAME, C0, C0_1
ENDIF
END SUBROUTINE DIFFC0

SUBROUTINE DIFFC1 (CDNAME, C1, C1_1)
CHARACTER (LEN=*) :: CDNAME
CHARACTER (LEN=*) :: C1 (:), C1_1 (:)
INTEGER :: I1
DO I1 = 1, SIZE (C1, 1)
  IF (C1 (I1) /= C1_1 (I1)) THEN
    WRITE (*, '(A32,I12,A,A)') CDNAME, I1, C1 (I1), C1_1 (I1)
  ENDIF
ENDDO
END SUBROUTINE DIFFC1

SUBROUTINE DIFFC2 (CDNAME, C2, C2_1)
CHARACTER (LEN=*) :: CDNAME
CHARACTER (LEN=*) :: C2 (:,:), C2_1 (:,:)
INTEGER :: I1, I2
DO I1 = 1, SIZE (C2, 1)
DO I2 = 1, SIZE (C2, 2)
  IF (C2 (I1, I2) /= C2_1 (I1, I2)) THEN
    WRITE (*, '(A32,I12,I12,A,A)') CDNAME, I1, I2, C2 (I1, I2), C2_1 (I1, I2)
  ENDIF
ENDDO
ENDDO
END SUBROUTINE DIFFC2

SUBROUTINE LOADC0 (ILUN, C0)
INTEGER           :: ILUN
CHARACTER (LEN=*) :: C0
READ (ILUN) C0
END SUBROUTINE LOADC0

SUBROUTINE LOADC1 (ILUN, C1)
INTEGER                   :: ILUN
CHARACTER (LEN=*), POINTER :: C1 (:)
INTEGER :: IL (1), IB (1)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (C1 (IL (1): IB (1)))
READ (ILUN) C1
END SUBROUTINE LOADC1

SUBROUTINE LOADC2 (ILUN, C2)
INTEGER                   :: ILUN
CHARACTER (LEN=*), POINTER :: C2 (:,:)
INTEGER :: IL (2), IB (2)
READ (ILUN) IL
READ (ILUN) IB
ALLOCATE (C2 (IL (1): IB (1), IL (2): IB (2)))
READ (ILUN) C2
END SUBROUTINE LOADC2

END MODULE LOAD_MOD

