MODULE LOAD_TEGSL_MOD

USE YEMGSL, ONLY : TEGSL

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGSL
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TEGSL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGSL), INTENT (OUT) :: YD

READ (KLUN) YD%RIPORE
READ (KLUN) YD%RJPORE
READ (KLUN) YD%REGPK
READ (KLUN) YD%RNOBILE
READ (KLUN) YD%RHSUD
READ (KLUN) YD%RMERCAT
READ (KLUN) YD%RLON0R
READ (KLUN) YD%RELONC
READ (KLUN) YD%RELATC
END SUBROUTINE


END MODULE
