MODULE LOAD_TOROG_MOD

USE YOMOROG, ONLY : TOROG

INTERFACE LOAD
MODULE PROCEDURE LOAD_TOROG
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TOROG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TOROG), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LOROG, LOROGL, LOROGLL, LOROGLM, LOROGM, LOROGMM
READ (KLUN) LOROG
IF (LOROG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OROG (IL1(1):IU1(1)))
  READ (KLUN) YD%OROG
ENDIF
READ (KLUN) LOROGL
IF (LOROGL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OROGL (IL1(1):IU1(1)))
  READ (KLUN) YD%OROGL
ENDIF
READ (KLUN) LOROGM
IF (LOROGM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OROGM (IL1(1):IU1(1)))
  READ (KLUN) YD%OROGM
ENDIF
READ (KLUN) LOROGLL
IF (LOROGLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OROGLL (IL1(1):IU1(1)))
  READ (KLUN) YD%OROGLL
ENDIF
READ (KLUN) LOROGMM
IF (LOROGMM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OROGMM (IL1(1):IU1(1)))
  READ (KLUN) YD%OROGMM
ENDIF
READ (KLUN) LOROGLM
IF (LOROGLM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%OROGLM (IL1(1):IU1(1)))
  READ (KLUN) YD%OROGLM
ENDIF
END SUBROUTINE


END MODULE
