MODULE LOAD_TGEM_MOD

USE YOMGEM, ONLY : TGEM

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGEM
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TGEM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGEM), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NGPTOT_CAP
READ (KLUN) YD%NGPTOTMX
READ (KLUN) YD%NGPTOTG
READ (KLUN) LNGPTOTL
IF (LNGPTOTL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGPTOTL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGPTOTL
ENDIF
READ (KLUN) YD%RDELXN
READ (KLUN) YD%SLHDP
READ (KLUN) YD%RMUCEN
READ (KLUN) YD%RLOCEN
READ (KLUN) YD%RSTRET
READ (KLUN) YD%NSTTYP
READ (KLUN) YD%NHTYP
READ (KLUN) YD%RNLGINC
READ (KLUN) YD%R4JP
READ (KLUN) YD%RC2P1
READ (KLUN) YD%RC2M1
READ (KLUN) YD%RCOR0
READ (KLUN) YD%RCOR1
READ (KLUN) LNLOEN
IF (LNLOEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOEN (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOEN
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
READ (KLUN) LNMEN
IF (LNMEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NMEN (IL1(1):IU1(1)))
  READ (KLUN) YD%NMEN
ENDIF
READ (KLUN) LNMENG
IF (LNMENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NMENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NMENG
ENDIF
READ (KLUN) LNDGLU
IF (LNDGLU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDGLU (IL1(1):IU1(1)))
  READ (KLUN) YD%NDGLU
ENDIF
READ (KLUN) LNSTAGP
IF (LNSTAGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSTAGP (IL1(1):IU1(1)))
  READ (KLUN) YD%NSTAGP
ENDIF
READ (KLUN) LNTSTAGP
IF (LNTSTAGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NTSTAGP (IL1(1):IU1(1)))
  READ (KLUN) YD%NTSTAGP
ENDIF
END SUBROUTINE


END MODULE
