MODULE LOAD_SL_STRUCT_MOD

USE EINT_MOD, ONLY : SL_STRUCT

INTERFACE LOAD
MODULE PROCEDURE LOAD_SL_STRUCT
END INTERFACE

CONTAINS

SUBROUTINE LOAD_SL_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (SL_STRUCT), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LDIST1GP, LLCOMPLAT, LLSLCOMM, LLSLCORE, LMASK_SL1, LMASK_SL2, LMASK_SL2T, LMASK_SLD, LMASK_SLTOT, LNLATGLO, LNLOENG, LNSLCOMM, LNSLCORE, LNSLEXT, LNSLMAP, LNSLOFF, LNSLONL, LNSLPTSEAST, LNSLPTSWEST, LNSLRECVPOS, LNSLRECVPTR, LNSLSENDPOS, LNSLSENDPTR, LNSLSTA
READ (KLUN) YD%CVER
READ (KLUN) YD%NSLGROUP
READ (KLUN) LNSLSTA
IF (LNSLSTA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLSTA (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLSTA
ENDIF
READ (KLUN) LNSLONL
IF (LNSLONL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLONL (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLONL
ENDIF
READ (KLUN) LNSLOFF
IF (LNSLOFF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLOFF (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLOFF
ENDIF
READ (KLUN) LNSLPTSWEST
IF (LNSLPTSWEST) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLPTSWEST (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLPTSWEST
ENDIF
READ (KLUN) LNSLPTSEAST
IF (LNSLPTSEAST) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLPTSEAST (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLPTSEAST
ENDIF
READ (KLUN) LNSLEXT
IF (LNSLEXT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSLEXT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSLEXT
ENDIF
READ (KLUN) LLCOMPLAT
IF (LLCOMPLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LCOMPLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%LCOMPLAT
ENDIF
READ (KLUN) LNLATGLO
IF (LNLATGLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLATGLO (IL1(1):IU1(1)))
  READ (KLUN) YD%NLATGLO
ENDIF
READ (KLUN) LDIST1GP
IF (LDIST1GP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%DIST1GP (IL1(1):IU1(1)))
  READ (KLUN) YD%DIST1GP
ENDIF
READ (KLUN) LNSLSENDPOS
IF (LNSLSENDPOS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLSENDPOS (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLSENDPOS
ENDIF
READ (KLUN) LNSLRECVPOS
IF (LNSLRECVPOS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLRECVPOS (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLRECVPOS
ENDIF
READ (KLUN) LNSLSENDPTR
IF (LNSLSENDPTR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLSENDPTR (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLSENDPTR
ENDIF
READ (KLUN) LNSLRECVPTR
IF (LNSLRECVPTR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLRECVPTR (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLRECVPTR
ENDIF
READ (KLUN) LNSLCOMM
IF (LNSLCOMM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLCOMM (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLCOMM
ENDIF
READ (KLUN) LLSLCOMM
IF (LLSLCOMM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%LSLCOMM (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%LSLCOMM
ENDIF
READ (KLUN) YD%NASLB1
READ (KLUN) YD%NASLB1_TRUE
READ (KLUN) YD%NSLPAD
READ (KLUN) YD%LSLT_ARRAYS_INIT
READ (KLUN) YD%LSLONDEM
READ (KLUN) YD%LSLONDEM_ACTIVE
READ (KLUN) YD%NUNUSEDHALO
READ (KLUN) YD%DISTUNUSEDHALO
READ (KLUN) LMASK_SL1
IF (LMASK_SL1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SL1 (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SL1
ENDIF
READ (KLUN) LMASK_SL2
IF (LMASK_SL2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SL2 (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SL2
ENDIF
READ (KLUN) LMASK_SL2T
IF (LMASK_SL2T) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASK_SL2T (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%MASK_SL2T
ENDIF
READ (KLUN) LMASK_SLD
IF (LMASK_SLD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SLD (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SLD
ENDIF
READ (KLUN) YD%NSLPROCS
READ (KLUN) YD%NSLRPT
READ (KLUN) YD%NSLSPT
READ (KLUN) YD%NSLWIDEN
READ (KLUN) YD%NSLWIDES
READ (KLUN) YD%NSLWIDEE
READ (KLUN) YD%NSLWIDEW
READ (KLUN) YD%NSLWIDE
READ (KLUN) LNSLMAP
IF (LNSLMAP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSLMAP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSLMAP
ENDIF
READ (KLUN) LNSLCORE
IF (LNSLCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSLCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%NSLCORE
ENDIF
READ (KLUN) LLSLCORE
IF (LLSLCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LSLCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%LSLCORE
ENDIF
READ (KLUN) LMASK_SLTOT
IF (LMASK_SLTOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MASK_SLTOT (IL1(1):IU1(1)))
  READ (KLUN) YD%MASK_SLTOT
ENDIF
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NDGUXL
READ (KLUN) YD%NDLUNG
READ (KLUN) YD%NDLUXG
READ (KLUN) YD%NDGUNG
READ (KLUN) YD%NDGUXG
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
END SUBROUTINE


END MODULE
