MODULE LOAD_TSLREP_MOD

USE YOMSLREP, ONLY : TSLREP

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSLREP
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TSLREP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLREP), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN
READ (KLUN) YD%NGPTOTAD
READ (KLUN) LNADMAP
IF (LNADMAP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NADMAP (IL1(1):IU1(1)))
  READ (KLUN) YD%NADMAP
ENDIF
READ (KLUN) LNADCORE
IF (LNADCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NADCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%NADCORE
ENDIF
READ (KLUN) LLADCORE
IF (LLADCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LADCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%LADCORE
ENDIF
READ (KLUN) LRSASIGN
IF (LRSASIGN) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSASIGN (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSASIGN
ENDIF
END SUBROUTINE


END MODULE
