MODULE LOAD_TYPE_GFLD_MOD

USE YOM_YGFL, ONLY : TYPE_GFLD

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_GFLD
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TYPE_GFLD (KLUN, YD)
USE LOAD_TYPE_GFL_COMP_MOD
USE LOAD_TYPE_GFL_NAML_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_GFLD), INTENT (OUT) :: YD
INTEGER :: J1, J2
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYA, LYAERAOT, LYAERLISI, LYAERO, LYAEROUT, LYCHEM, LYCPF, LYCRM, LYCVGQ, LYCVV, LYDAL, LYDOM, LYEFB1, LYEFB2, LYEFB3, LYERA40, LYEXT, LYEZDIAG, LYFORC, LYFQTUR, LYFSTUR, LYG, LYGHG, LYH, LYI, LYICONV, LYIRAD, LYL, LYLASTCOMP, LYLCONV, LYLIMA, LYLRAD, LYLRCH4, LYMXL, LYNOGW, LYO3, LYPHYS, LYQ, LYQVA, LYR, LYRCONV, LYRKTH, LYRKTQC, LYRKTQV, LYRSPEC, LYS, LYSCONV, LYSDSAT, LYSHTUR, LYSLDIA, LYSPF, LYSRC, LYTKE, LYTTE, LYUAL, LYUEN, LYUNEBH, LYUOM, LYUVP
READ (KLUN) YD%NUMFLDS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDS"
READ (KLUN) YD%NDERS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDERS"
READ (KLUN) YD%NUMSPFLDS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMSPFLDS"
READ (KLUN) YD%NUMGPFLDS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMGPFLDS"
READ (KLUN) YD%NUMFLDS9 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDS9"
READ (KLUN) YD%NUMFLDS1 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDS1"
READ (KLUN) YD%NUMSPFLDS1 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMSPFLDS1"
READ (KLUN) YD%NUMFLDS5 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDS5"
READ (KLUN) YD%NUMFLDSPHY ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDSPHY"
READ (KLUN) YD%NUMFLDS_SPL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDS_SPL"
READ (KLUN) YD%NUMFLDS_SL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDS_SL1"
READ (KLUN) YD%NUMFLDSPC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDSPC"
READ (KLUN) YD%NDIM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIM"
READ (KLUN) YD%NUMFLDSPT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUMFLDSPT"
READ (KLUN) YD%NDIM0 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIM0"
READ (KLUN) YD%NDIM9 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIM9"
READ (KLUN) YD%NDIM1 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIM1"
READ (KLUN) YD%NDIM5 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIM5"
READ (KLUN) YD%NDIMSLP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIMSLP"
READ (KLUN) YD%NDIM_SPL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIM_SPL"
READ (KLUN) YD%NDIMPT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIMPT"
READ (KLUN) YD%NDIMPC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDIMPC"
READ (KLUN) YD%NGFL_EXT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NGFL_EXT"
READ (KLUN) YD%NGFL_FORC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NGFL_FORC"
READ (KLUN) YD%NGFL_EZDIAG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NGFL_EZDIAG"
READ (KLUN) YD%NGHG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NGHG"
READ (KLUN) YD%NAERO ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NAERO"
READ (KLUN) YD%NACTAERO ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NACTAERO"
READ (KLUN) YD%NDDHAERO ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NDDHAERO"
READ (KLUN) YD%NERA40 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NERA40"
READ (KLUN) YD%NNOGW ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NNOGW"
READ (KLUN) YD%NAEROUT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NAEROUT"
READ (KLUN) YD%NUVP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NUVP"
READ (KLUN) YD%NSLDIA ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NSLDIA"
READ (KLUN) YD%NSLDIAGP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NSLDIAGP"
READ (KLUN) YD%NGFL_PHYS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NGFL_PHYS"
READ (KLUN) YD%NCRM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCRM"
READ (KLUN) YD%LAERCHEM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LAERCHEM"
READ (KLUN) YD%LTRCMFIX ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFIX"
READ (KLUN) YD%LTRCMFIX_PS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFIX_PS"
READ (KLUN) YD%LAERAOT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LAERAOT"
READ (KLUN) YD%LAERLISI ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LAERLISI"
READ (KLUN) YD%LAEROUT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LAEROUT"
READ (KLUN) YD%LUVPOUT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LUVPOUT"
READ (KLUN) YD%LSPPTGFL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LSPPTGFL"
READ (KLUN) YD%NGEMS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NGEMS"
READ (KLUN) YD%NCHEM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCHEM"
READ (KLUN) YD%NCHEM_ASSIM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCHEM_ASSIM"
READ (KLUN) YD%NCHEM_FLX ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCHEM_FLX"
READ (KLUN) YD%NCHEM_DV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCHEM_DV"
READ (KLUN) YD%NCHEM_TC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCHEM_TC"
READ (KLUN) YD%NCHEM_SCV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NCHEM_SCV"
READ (KLUN) YD%NLIMA ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NLIMA"
READ (KLUN) YD%NAERO_WVL_DIAG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NAERO_WVL_DIAG"
READ (KLUN) YD%NAERO_WVL_DIAG_TYPES ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NAERO_WVL_DIAG_TYPES"
READ (KLUN) YD%NNEGAFIX ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NNEGAFIX"
READ (KLUN) YD%NOPTNEGFIX ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NOPTNEGFIX"
READ (KLUN) YD%LQM3DCONS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LQM3DCONS"
READ (KLUN) YD%LADVNEGFIX ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LADVNEGFIX"
READ (KLUN) YD%LTRCMFBC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFBC"
READ (KLUN) YD%LTRCMFPR ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFPR"
READ (KLUN) YD%LTRCMFMG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFMG"
READ (KLUN) YD%LTRCMFP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFP"
READ (KLUN) YD%LTRCMFA_DIF ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFA_DIF"
READ (KLUN) YD%LTRCMFA_LAP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFA_LAP"
READ (KLUN) YD%LTRCMFA_VER ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LTRCMFA_VER"
READ (KLUN) YD%LEXTRADF ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%LEXTRADF"
READ (KLUN) YD%NFLDSFIX ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NFLDSFIX"
READ (KLUN) YD%NOPTMFBC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NOPTMFBC"
READ (KLUN) YD%NOPTMFPR ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NOPTMFPR"
READ (KLUN) YD%NOPTVFE ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NOPTVFE"
READ (KLUN) YD%NMFDIAGLEV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NMFDIAGLEV"
READ (KLUN) YD%NMFIXFLDS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NMFIXFLDS"
READ (KLUN) YD%NNEGFLDS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%NNEGFLDS"
READ (KLUN) YD%ZMFIXEPS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) YD%ZMFIXEPS"
DO J1 = LBOUND (YD%YCOMP, 1), UBOUND (YD%YCOMP, 1)
  CALL LOAD (KLUN, YD%YCOMP (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YCOMP (J1))"
ENDDO
READ (KLUN) LYLASTCOMP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYLASTCOMP"
IF (LYLASTCOMP) THEN
  ALLOCATE (YD%YLASTCOMP)
  CALL LOAD (KLUN, YD%YLASTCOMP) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YLASTCOMP)"
ELSE
  NULLIFY (YD%YLASTCOMP)
ENDIF
READ (KLUN) LYQ ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYQ"
IF (LYQ) THEN
  ALLOCATE (YD%YQ)
  CALL LOAD (KLUN, YD%YQ) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YQ)"
ELSE
  NULLIFY (YD%YQ)
ENDIF
READ (KLUN) LYI ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYI"
IF (LYI) THEN
  ALLOCATE (YD%YI)
  CALL LOAD (KLUN, YD%YI) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YI)"
ELSE
  NULLIFY (YD%YI)
ENDIF
READ (KLUN) LYL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYL"
IF (LYL) THEN
  ALLOCATE (YD%YL)
  CALL LOAD (KLUN, YD%YL) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YL)"
ELSE
  NULLIFY (YD%YL)
ENDIF
READ (KLUN) LYLCONV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYLCONV"
IF (LYLCONV) THEN
  ALLOCATE (YD%YLCONV)
  CALL LOAD (KLUN, YD%YLCONV) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YLCONV)"
ELSE
  NULLIFY (YD%YLCONV)
ENDIF
READ (KLUN) LYICONV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYICONV"
IF (LYICONV) THEN
  ALLOCATE (YD%YICONV)
  CALL LOAD (KLUN, YD%YICONV) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YICONV)"
ELSE
  NULLIFY (YD%YICONV)
ENDIF
READ (KLUN) LYRCONV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYRCONV"
IF (LYRCONV) THEN
  ALLOCATE (YD%YRCONV)
  CALL LOAD (KLUN, YD%YRCONV) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YRCONV)"
ELSE
  NULLIFY (YD%YRCONV)
ENDIF
READ (KLUN) LYSCONV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYSCONV"
IF (LYSCONV) THEN
  ALLOCATE (YD%YSCONV)
  CALL LOAD (KLUN, YD%YSCONV) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YSCONV)"
ELSE
  NULLIFY (YD%YSCONV)
ENDIF
READ (KLUN) LYIRAD ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYIRAD"
IF (LYIRAD) THEN
  ALLOCATE (YD%YIRAD)
  CALL LOAD (KLUN, YD%YIRAD) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YIRAD)"
ELSE
  NULLIFY (YD%YIRAD)
ENDIF
READ (KLUN) LYLRAD ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYLRAD"
IF (LYLRAD) THEN
  ALLOCATE (YD%YLRAD)
  CALL LOAD (KLUN, YD%YLRAD) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YLRAD)"
ELSE
  NULLIFY (YD%YLRAD)
ENDIF
READ (KLUN) LYS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYS"
IF (LYS) THEN
  ALLOCATE (YD%YS)
  CALL LOAD (KLUN, YD%YS) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YS)"
ELSE
  NULLIFY (YD%YS)
ENDIF
READ (KLUN) LYR ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYR"
IF (LYR) THEN
  ALLOCATE (YD%YR)
  CALL LOAD (KLUN, YD%YR) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YR)"
ELSE
  NULLIFY (YD%YR)
ENDIF
READ (KLUN) LYG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYG"
IF (LYG) THEN
  ALLOCATE (YD%YG)
  CALL LOAD (KLUN, YD%YG) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YG)"
ELSE
  NULLIFY (YD%YG)
ENDIF
READ (KLUN) LYH ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYH"
IF (LYH) THEN
  ALLOCATE (YD%YH)
  CALL LOAD (KLUN, YD%YH) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YH)"
ELSE
  NULLIFY (YD%YH)
ENDIF
READ (KLUN) LYTKE ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYTKE"
IF (LYTKE) THEN
  ALLOCATE (YD%YTKE)
  CALL LOAD (KLUN, YD%YTKE) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YTKE)"
ELSE
  NULLIFY (YD%YTKE)
ENDIF
READ (KLUN) LYTTE ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYTTE"
IF (LYTTE) THEN
  ALLOCATE (YD%YTTE)
  CALL LOAD (KLUN, YD%YTTE) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YTTE)"
ELSE
  NULLIFY (YD%YTTE)
ENDIF
READ (KLUN) LYEFB1 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYEFB1"
IF (LYEFB1) THEN
  ALLOCATE (YD%YEFB1)
  CALL LOAD (KLUN, YD%YEFB1) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YEFB1)"
ELSE
  NULLIFY (YD%YEFB1)
ENDIF
READ (KLUN) LYEFB2 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYEFB2"
IF (LYEFB2) THEN
  ALLOCATE (YD%YEFB2)
  CALL LOAD (KLUN, YD%YEFB2) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YEFB2)"
ELSE
  NULLIFY (YD%YEFB2)
ENDIF
READ (KLUN) LYEFB3 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYEFB3"
IF (LYEFB3) THEN
  ALLOCATE (YD%YEFB3)
  CALL LOAD (KLUN, YD%YEFB3) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YEFB3)"
ELSE
  NULLIFY (YD%YEFB3)
ENDIF
READ (KLUN) LYA ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYA"
IF (LYA) THEN
  ALLOCATE (YD%YA)
  CALL LOAD (KLUN, YD%YA) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YA)"
ELSE
  NULLIFY (YD%YA)
ENDIF
READ (KLUN) LYO3 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYO3"
IF (LYO3) THEN
  ALLOCATE (YD%YO3)
  CALL LOAD (KLUN, YD%YO3) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YO3)"
ELSE
  NULLIFY (YD%YO3)
ENDIF
READ (KLUN) LYSRC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYSRC"
IF (LYSRC) THEN
  ALLOCATE (YD%YSRC)
  CALL LOAD (KLUN, YD%YSRC) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YSRC)"
ELSE
  NULLIFY (YD%YSRC)
ENDIF
READ (KLUN) LYMXL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYMXL"
IF (LYMXL) THEN
  ALLOCATE (YD%YMXL)
  CALL LOAD (KLUN, YD%YMXL) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YMXL)"
ELSE
  NULLIFY (YD%YMXL)
ENDIF
READ (KLUN) LYSHTUR ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYSHTUR"
IF (LYSHTUR) THEN
  ALLOCATE (YD%YSHTUR)
  CALL LOAD (KLUN, YD%YSHTUR) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YSHTUR)"
ELSE
  NULLIFY (YD%YSHTUR)
ENDIF
READ (KLUN) LYFQTUR ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYFQTUR"
IF (LYFQTUR) THEN
  ALLOCATE (YD%YFQTUR)
  CALL LOAD (KLUN, YD%YFQTUR) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YFQTUR)"
ELSE
  NULLIFY (YD%YFQTUR)
ENDIF
READ (KLUN) LYFSTUR ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYFSTUR"
IF (LYFSTUR) THEN
  ALLOCATE (YD%YFSTUR)
  CALL LOAD (KLUN, YD%YFSTUR) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YFSTUR)"
ELSE
  NULLIFY (YD%YFSTUR)
ENDIF
READ (KLUN) LYCPF ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYCPF"
IF (LYCPF) THEN
  ALLOCATE (YD%YCPF)
  CALL LOAD (KLUN, YD%YCPF) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YCPF)"
ELSE
  NULLIFY (YD%YCPF)
ENDIF
READ (KLUN) LYSPF ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYSPF"
IF (LYSPF) THEN
  ALLOCATE (YD%YSPF)
  CALL LOAD (KLUN, YD%YSPF) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YSPF)"
ELSE
  NULLIFY (YD%YSPF)
ENDIF
READ (KLUN) LYCVGQ ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYCVGQ"
IF (LYCVGQ) THEN
  ALLOCATE (YD%YCVGQ)
  CALL LOAD (KLUN, YD%YCVGQ) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YCVGQ)"
ELSE
  NULLIFY (YD%YCVGQ)
ENDIF
READ (KLUN) LYQVA ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYQVA"
IF (LYQVA) THEN
  ALLOCATE (YD%YQVA)
  CALL LOAD (KLUN, YD%YQVA) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YQVA)"
ELSE
  NULLIFY (YD%YQVA)
ENDIF
READ (KLUN) LYGHG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYGHG"
IF (LYGHG) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YGHG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YGHG, 1), UBOUND (YD%YGHG, 1)
    CALL LOAD (KLUN, YD%YGHG (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YGHG (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YGHG)
ENDIF
READ (KLUN) LYCHEM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYCHEM"
IF (LYCHEM) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YCHEM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YCHEM, 1), UBOUND (YD%YCHEM, 1)
    CALL LOAD (KLUN, YD%YCHEM (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YCHEM (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YCHEM)
ENDIF
READ (KLUN) LYAERO ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYAERO"
IF (LYAERO) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YAERO (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAERO, 1), UBOUND (YD%YAERO, 1)
    CALL LOAD (KLUN, YD%YAERO (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YAERO (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YAERO)
ENDIF
READ (KLUN) LYLRCH4 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYLRCH4"
IF (LYLRCH4) THEN
  ALLOCATE (YD%YLRCH4)
  CALL LOAD (KLUN, YD%YLRCH4) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YLRCH4)"
ELSE
  NULLIFY (YD%YLRCH4)
ENDIF
READ (KLUN) LYFORC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYFORC"
IF (LYFORC) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YFORC (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YFORC, 1), UBOUND (YD%YFORC, 1)
    CALL LOAD (KLUN, YD%YFORC (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YFORC (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YFORC)
ENDIF
READ (KLUN) LYEZDIAG ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYEZDIAG"
IF (LYEZDIAG) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YEZDIAG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YEZDIAG, 1), UBOUND (YD%YEZDIAG, 1)
    CALL LOAD (KLUN, YD%YEZDIAG (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YEZDIAG (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YEZDIAG)
ENDIF
READ (KLUN) LYERA40 ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYERA40"
IF (LYERA40) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YERA40 (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YERA40, 1), UBOUND (YD%YERA40, 1)
    CALL LOAD (KLUN, YD%YERA40 (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YERA40 (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YERA40)
ENDIF
READ (KLUN) LYNOGW ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYNOGW"
IF (LYNOGW) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YNOGW (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YNOGW, 1), UBOUND (YD%YNOGW, 1)
    CALL LOAD (KLUN, YD%YNOGW (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YNOGW (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YNOGW)
ENDIF
READ (KLUN) LYSLDIA ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYSLDIA"
IF (LYSLDIA) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YSLDIA (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YSLDIA, 1), UBOUND (YD%YSLDIA, 1)
    CALL LOAD (KLUN, YD%YSLDIA (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YSLDIA (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YSLDIA)
ENDIF
READ (KLUN) LYAERAOT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYAERAOT"
IF (LYAERAOT) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YAERAOT (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAERAOT, 1), UBOUND (YD%YAERAOT, 1)
    CALL LOAD (KLUN, YD%YAERAOT (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YAERAOT (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YAERAOT)
ENDIF
READ (KLUN) LYAERLISI ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYAERLISI"
IF (LYAERLISI) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YAERLISI (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAERLISI, 1), UBOUND (YD%YAERLISI, 1)
    CALL LOAD (KLUN, YD%YAERLISI (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YAERLISI (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YAERLISI)
ENDIF
READ (KLUN) LYAEROUT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYAEROUT"
IF (LYAEROUT) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YAEROUT (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YAEROUT, 1), UBOUND (YD%YAEROUT, 1)
    CALL LOAD (KLUN, YD%YAEROUT (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YAEROUT (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YAEROUT)
ENDIF
READ (KLUN) LYUVP ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYUVP"
IF (LYUVP) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YUVP (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YUVP, 1), UBOUND (YD%YUVP, 1)
    CALL LOAD (KLUN, YD%YUVP (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YUVP (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YUVP)
ENDIF
READ (KLUN) LYPHYS ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYPHYS"
IF (LYPHYS) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YPHYS (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YPHYS, 1), UBOUND (YD%YPHYS, 1)
    CALL LOAD (KLUN, YD%YPHYS (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YPHYS (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YPHYS)
ENDIF
READ (KLUN) LYRSPEC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYRSPEC"
IF (LYRSPEC) THEN
  ALLOCATE (YD%YRSPEC)
  CALL LOAD (KLUN, YD%YRSPEC) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YRSPEC)"
ELSE
  NULLIFY (YD%YRSPEC)
ENDIF
READ (KLUN) LYSDSAT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYSDSAT"
IF (LYSDSAT) THEN
  ALLOCATE (YD%YSDSAT)
  CALL LOAD (KLUN, YD%YSDSAT) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YSDSAT)"
ELSE
  NULLIFY (YD%YSDSAT)
ENDIF
READ (KLUN) LYCVV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYCVV"
IF (LYCVV) THEN
  ALLOCATE (YD%YCVV)
  CALL LOAD (KLUN, YD%YCVV) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YCVV)"
ELSE
  NULLIFY (YD%YCVV)
ENDIF
READ (KLUN) LYRKTH ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYRKTH"
IF (LYRKTH) THEN
  ALLOCATE (YD%YRKTH)
  CALL LOAD (KLUN, YD%YRKTH) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YRKTH)"
ELSE
  NULLIFY (YD%YRKTH)
ENDIF
READ (KLUN) LYRKTQV ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYRKTQV"
IF (LYRKTQV) THEN
  ALLOCATE (YD%YRKTQV)
  CALL LOAD (KLUN, YD%YRKTQV) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YRKTQV)"
ELSE
  NULLIFY (YD%YRKTQV)
ENDIF
READ (KLUN) LYRKTQC ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYRKTQC"
IF (LYRKTQC) THEN
  ALLOCATE (YD%YRKTQC)
  CALL LOAD (KLUN, YD%YRKTQC) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YRKTQC)"
ELSE
  NULLIFY (YD%YRKTQC)
ENDIF
READ (KLUN) LYUOM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYUOM"
IF (LYUOM) THEN
  ALLOCATE (YD%YUOM)
  CALL LOAD (KLUN, YD%YUOM) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YUOM)"
ELSE
  NULLIFY (YD%YUOM)
ENDIF
READ (KLUN) LYUAL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYUAL"
IF (LYUAL) THEN
  ALLOCATE (YD%YUAL)
  CALL LOAD (KLUN, YD%YUAL) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YUAL)"
ELSE
  NULLIFY (YD%YUAL)
ENDIF
READ (KLUN) LYDOM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYDOM"
IF (LYDOM) THEN
  ALLOCATE (YD%YDOM)
  CALL LOAD (KLUN, YD%YDOM) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YDOM)"
ELSE
  NULLIFY (YD%YDOM)
ENDIF
READ (KLUN) LYDAL ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYDAL"
IF (LYDAL) THEN
  ALLOCATE (YD%YDAL)
  CALL LOAD (KLUN, YD%YDAL) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YDAL)"
ELSE
  NULLIFY (YD%YDAL)
ENDIF
READ (KLUN) LYUEN ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYUEN"
IF (LYUEN) THEN
  ALLOCATE (YD%YUEN)
  CALL LOAD (KLUN, YD%YUEN) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YUEN)"
ELSE
  NULLIFY (YD%YUEN)
ENDIF
READ (KLUN) LYUNEBH ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYUNEBH"
IF (LYUNEBH) THEN
  ALLOCATE (YD%YUNEBH)
  CALL LOAD (KLUN, YD%YUNEBH) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YUNEBH)"
ELSE
  NULLIFY (YD%YUNEBH)
ENDIF
READ (KLUN) LYCRM ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYCRM"
IF (LYCRM) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YCRM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YCRM, 1), UBOUND (YD%YCRM, 1)
    CALL LOAD (KLUN, YD%YCRM (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YCRM (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YCRM)
ENDIF
READ (KLUN) LYLIMA ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYLIMA"
IF (LYLIMA) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1"
  ALLOCATE (YD%YLIMA (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YLIMA, 1), UBOUND (YD%YLIMA, 1)
    CALL LOAD (KLUN, YD%YLIMA (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YLIMA (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YLIMA)
ENDIF
READ (KLUN) LYEXT ; WRITE (0, *) __FILE__, ':', __LINE__, "READ (KLUN) LYEXT"
IF (LYEXT) THEN
  READ (KLUN) IL1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IL1", IL1, "<<"
  READ (KLUN) IU1 ; WRITE (0, *) __FILE__, ':', __LINE__, "  READ (KLUN) IU1", IU1, "<<"
  ALLOCATE (YD%YEXT (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YEXT, 1), UBOUND (YD%YEXT, 1)
    CALL LOAD (KLUN, YD%YEXT (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YEXT (J1))"
  ENDDO
ELSE
  NULLIFY (YD%YEXT)
ENDIF
CALL LOAD (KLUN, YD%YQ_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YQ_NL)"
CALL LOAD (KLUN, YD%YI_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YI_NL)"
CALL LOAD (KLUN, YD%YL_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YL_NL)"
CALL LOAD (KLUN, YD%YLCONV_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YLCONV_NL)"
CALL LOAD (KLUN, YD%YICONV_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YICONV_NL)"
CALL LOAD (KLUN, YD%YRCONV_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YRCONV_NL)"
CALL LOAD (KLUN, YD%YSCONV_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YSCONV_NL)"
CALL LOAD (KLUN, YD%YIRAD_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YIRAD_NL)"
CALL LOAD (KLUN, YD%YLRAD_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YLRAD_NL)"
CALL LOAD (KLUN, YD%YS_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YS_NL)"
CALL LOAD (KLUN, YD%YR_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YR_NL)"
CALL LOAD (KLUN, YD%YG_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YG_NL)"
CALL LOAD (KLUN, YD%YH_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YH_NL)"
CALL LOAD (KLUN, YD%YTKE_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YTKE_NL)"
CALL LOAD (KLUN, YD%YTTE_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YTTE_NL)"
CALL LOAD (KLUN, YD%YEFB1_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YEFB1_NL)"
CALL LOAD (KLUN, YD%YEFB2_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YEFB2_NL)"
CALL LOAD (KLUN, YD%YEFB3_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YEFB3_NL)"
CALL LOAD (KLUN, YD%YA_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YA_NL)"
CALL LOAD (KLUN, YD%YO3_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YO3_NL)"
CALL LOAD (KLUN, YD%YSRC_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YSRC_NL)"
CALL LOAD (KLUN, YD%YMXL_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YMXL_NL)"
CALL LOAD (KLUN, YD%YSHTUR_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YSHTUR_NL)"
CALL LOAD (KLUN, YD%YFQTUR_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YFQTUR_NL)"
CALL LOAD (KLUN, YD%YFSTUR_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YFSTUR_NL)"
CALL LOAD (KLUN, YD%YCPF_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YCPF_NL)"
CALL LOAD (KLUN, YD%YSPF_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YSPF_NL)"
CALL LOAD (KLUN, YD%YCVGQ_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YCVGQ_NL)"
CALL LOAD (KLUN, YD%YQVA_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YQVA_NL)"
DO J1 = LBOUND (YD%YGHG_NL, 1), UBOUND (YD%YGHG_NL, 1)
  CALL LOAD (KLUN, YD%YGHG_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YGHG_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YCHEM_NL, 1), UBOUND (YD%YCHEM_NL, 1)
  CALL LOAD (KLUN, YD%YCHEM_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YCHEM_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YAERO_NL, 1), UBOUND (YD%YAERO_NL, 1)
  CALL LOAD (KLUN, YD%YAERO_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YAERO_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YERA40_NL, 1), UBOUND (YD%YERA40_NL, 1)
  CALL LOAD (KLUN, YD%YERA40_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YERA40_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YNOGW_NL, 1), UBOUND (YD%YNOGW_NL, 1)
  CALL LOAD (KLUN, YD%YNOGW_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YNOGW_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YSLDIA_NL, 1), UBOUND (YD%YSLDIA_NL, 1)
  CALL LOAD (KLUN, YD%YSLDIA_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YSLDIA_NL (J1))"
ENDDO
CALL LOAD (KLUN, YD%YLRCH4_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YLRCH4_NL)"
DO J1 = LBOUND (YD%YAERAOT_NL, 1), UBOUND (YD%YAERAOT_NL, 1)
  CALL LOAD (KLUN, YD%YAERAOT_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YAERAOT_NL (J1))"
ENDDO
DO J2 = LBOUND (YD%YAERLISI_NL, 2), UBOUND (YD%YAERLISI_NL, 2)
  DO J1 = LBOUND (YD%YAERLISI_NL, 1), UBOUND (YD%YAERLISI_NL, 1)
    CALL LOAD (KLUN, YD%YAERLISI_NL (J1, J2)) ; WRITE (0, *) __FILE__, ':', __LINE__, "    CALL LOAD (KLUN, YD%YAERLISI_NL (J1, J2))"
  ENDDO
ENDDO
DO J1 = LBOUND (YD%YAEROUT_NL, 1), UBOUND (YD%YAEROUT_NL, 1)
  CALL LOAD (KLUN, YD%YAEROUT_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YAEROUT_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YUVP_NL, 1), UBOUND (YD%YUVP_NL, 1)
  CALL LOAD (KLUN, YD%YUVP_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YUVP_NL (J1))"
ENDDO
CALL LOAD (KLUN, YD%YRKTH_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YRKTH_NL)"
CALL LOAD (KLUN, YD%YRKTQV_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YRKTQV_NL)"
CALL LOAD (KLUN, YD%YRKTQC_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YRKTQC_NL)"
DO J1 = LBOUND (YD%YPHYS_NL, 1), UBOUND (YD%YPHYS_NL, 1)
  CALL LOAD (KLUN, YD%YPHYS_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YPHYS_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YCRM_NL, 1), UBOUND (YD%YCRM_NL, 1)
  CALL LOAD (KLUN, YD%YCRM_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YCRM_NL (J1))"
ENDDO
CALL LOAD (KLUN, YD%YRSPEC_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YRSPEC_NL)"
CALL LOAD (KLUN, YD%YSDSAT_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YSDSAT_NL)"
CALL LOAD (KLUN, YD%YCVV_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YCVV_NL)"
DO J1 = LBOUND (YD%YFORC_NL, 1), UBOUND (YD%YFORC_NL, 1)
  CALL LOAD (KLUN, YD%YFORC_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YFORC_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YEZDIAG_NL, 1), UBOUND (YD%YEZDIAG_NL, 1)
  CALL LOAD (KLUN, YD%YEZDIAG_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YEZDIAG_NL (J1))"
ENDDO
DO J1 = LBOUND (YD%YEXT_NL, 1), UBOUND (YD%YEXT_NL, 1)
  CALL LOAD (KLUN, YD%YEXT_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YEXT_NL (J1))"
ENDDO
CALL LOAD (KLUN, YD%YUOM_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YUOM_NL)"
CALL LOAD (KLUN, YD%YUAL_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YUAL_NL)"
CALL LOAD (KLUN, YD%YDOM_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YDOM_NL)"
CALL LOAD (KLUN, YD%YDAL_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YDAL_NL)"
CALL LOAD (KLUN, YD%YUEN_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YUEN_NL)"
CALL LOAD (KLUN, YD%YUNEBH_NL) ; WRITE (0, *) __FILE__, ':', __LINE__, "CALL LOAD (KLUN, YD%YUNEBH_NL)"
WRITE (0, *) __FILE__, ':', __LINE__, LBOUND (YD%YLIMA_NL, 1)
WRITE (0, *) __FILE__, ':', __LINE__, UBOUND (YD%YLIMA_NL, 1)
DO J1 = LBOUND (YD%YLIMA_NL, 1), UBOUND (YD%YLIMA_NL, 1)
  CALL LOAD (KLUN, YD%YLIMA_NL (J1)) ; WRITE (0, *) __FILE__, ':', __LINE__, "  CALL LOAD (KLUN, YD%YLIMA_NL (J1))", J1
ENDDO
END SUBROUTINE


END MODULE
