SUBROUTINE _PP_MODEL_DYNAMICS_TYPE_(YDML_DYN)

USE MODEL_DYNAMICS_MOD

IMPLICIT NONE

TYPE(MODEL_DYNAMICS_TYPE)   ,INTENT(INOUT) :: YDML_DYN

INTEGER :: I, J

PRINT *, " YDML_DYN%YRSPNG%LNSPONGE "
PRINT *, YDML_DYN%YRSPNG%LNSPONGE
PRINT *, " YDML_DYN%YRSPNG%RSPONGF "
DO J = 1, SIZE (YDML_DYN%YRSPNG%RSPONGF, 2)
DO I = 1, SIZE (YDML_DYN%YRSPNG%RSPONGF, 1)
  PRINT *, YDML_DYN%YRSPNG%RSPONGF (I, J)
ENDDO
ENDDO

PRINT *, " YDML_DYN%YRDYN%RDIVOR "
DO J = 1, SIZE (YDML_DYN%YRDYN%RDIVOR, 2)
DO I = 1, SIZE (YDML_DYN%YRDYN%RDIVOR, 1)
  PRINT *, YDML_DYN%YRDYN%RDIVOR (I, J)
ENDDO
ENDDO

PRINT *, " YDML_DYN%YYTLSCAW%M_WDLO "
PRINT *, YDML_DYN%YYTLSCAW%M_WDLO 
PRINT *, " YDML_DYN%YYTLSCAW%M_WDLAT "
PRINT *, YDML_DYN%YYTLSCAW%M_WDLAT 
PRINT *, " YDML_DYN%YYTLSCAW%NDIM "
PRINT *, YDML_DYN%YYTLSCAW%NDIM 

END
