SUBROUTINE _PP_MODEL_GENERAL_CONF_TYPE_(YDML_GCONF)

USE MODEL_GENERAL_CONF_MOD

IMPLICIT NONE

TYPE(MODEL_GENERAL_CONF_TYPE)   ,INTENT(INOUT) :: YDML_GCONF

INTEGER :: I, J

IF (ASSOCIATED (YDML_GCONF%GEOM)) THEN

PRINT *, " YDML_GCONF%GEOM%YRGEM%NGPTOT "
PRINT *, YDML_GCONF%GEOM%YRGEM%NGPTOT

PRINT *, " YDML_GCONF%GEOM%YRGEM%NGPTOTL "
DO J = 1, SIZE (YDML_GCONF%GEOM%YRGEM%NGPTOTL, 2)
DO I = 1, SIZE (YDML_GCONF%GEOM%YRGEM%NGPTOTL, 1)
  PRINT *, YDML_GCONF%GEOM%YRGEM%NGPTOTL (I, J)
ENDDO
ENDDO

PRINT *, " YDML_GCONF%GEOM%YRVAB%VALH "
DO I = 1, SIZE (YDML_GCONF%GEOM%YRVAB%VALH)
  PRINT *, YDML_GCONF%GEOM%YRVAB%VALH (I)
ENDDO

PRINT *, " YDML_GCONF%GEOM%YRCSGEOM%RCOLON "
DO I = 1, SIZE (YDML_GCONF%GEOM%YRCSGEOM)
  PRINT *, I
  DO J = 1, SIZE (YDML_GCONF%GEOM%YRCSGEOM (I)%RCOLON)
    PRINT *, YDML_GCONF%GEOM%YRCSGEOM (I)%RCOLON (J)
  ENDDO
ENDDO

ENDIF

PRINT *, " YDML_GCONF%YGFL%NUMFLDS "
PRINT *, YDML_GCONF%YGFL%NUMFLDS 

PRINT *, ASSOCIATED (YDML_GCONF%YGFL%YI)

IF (ASSOCIATED (YDML_GCONF%YGFL%YI)) THEN
  PRINT *, YDML_GCONF%YGFL%YI%CNAME
  PRINT *, YDML_GCONF%YGFL%YI%RCP
  PRINT *, YDML_GCONF%YGFL%YI%NREQIN
  PRINT *, YDML_GCONF%YGFL%YI%LREQOUT
ENDIF


END
