MODULE SLMOD

TYPE SL_STRUCT
  CHARACTER*2 :: CVER = '  '
  INTEGER, ALLOCATABLE :: NSLSTA (:)
  INTEGER, ALLOCATABLE :: NSLONL (:)
END TYPE

END MODULE

PROGRAM MAIN

USE SLMOD

IMPLICIT NONE

TYPE (SL_STRUCT) :: YDSL

INTERFACE
!$acc routine(TOTO) seq
SUBROUTINE TOTO(YDSL)
USE SLMOD
IMPLICIT NONE
TYPE(SL_STRUCT)   ,INTENT(INOUT) :: YDSL
END
END INTERFACE

INTEGER (KIND=4) :: I

!$acc enter data create (YDSL)

YDSL%CVER = 'SL'
!$acc update device (YDSL%CVER)

ALLOCATE (YDSL%NSLSTA (10))

DO I = 1, 10
YDSL%NSLSTA (I) = I
ENDDO

!$acc enter data create (YDSL%NSLSTA)
!$acc update device (YDSL%NSLSTA)
!$acc enter data attach (YDSL%NSLSTA)

ALLOCATE (YDSL%NSLONL (10))

DO I = 1, 10
YDSL%NSLONL (I) = 11-I
ENDDO

!$acc enter data create (YDSL%NSLONL)
!$acc update device (YDSL%NSLONL)
!$acc enter data attach (YDSL%NSLONL)

PRINT *, YDSL%CVER
DO I = 1, 10
PRINT *, YDSL%NSLSTA (I), YDSL%NSLONL (I)
ENDDO


!#acc serial copyin (YDSL,YDSL%CVER) 
!$acc serial default (none)

CALL TOTO (YDSL)

!$acc end serial

END

!$acc routine(TOTO) seq
SUBROUTINE TOTO(YDSL)

USE SLMOD

IMPLICIT NONE

TYPE(SL_STRUCT)   ,INTENT(INOUT) :: YDSL

INTEGER :: I

PRINT *, YDSL%CVER
DO I = 1, 10
PRINT *, YDSL%NSLSTA (I), YDSL%NSLONL (I)
ENDDO

END
