!> geometry derived type for the IFS model
!> separated from geometry_mod to break dependency issues with sugeometry

MODULE TYPE_GEOMETRY

USE YOMVERT  , ONLY : TVAB, TVETA, TVFE, TVERTICAL_GEOM
USE YOMSTA   , ONLY : TSTA
USE YOMLAP   , ONLY : TLAP
USE YOMLEG   , ONLY : TCSGLEG
USE YOMDIM   , ONLY : TDIM
USE YOMDIMV  , ONLY : TDIMV
USE YOMMP    , ONLY : TMP
USE YOMGEM   , ONLY : TGEM
USE YOMVSPLIP, ONLY : TVSPLIP
USE YOMVSLETA, ONLY : TVSLETA
USE YOMHSLMER, ONLY : THSLMER
USE YOMCSGEOM, ONLY : TCSGEOM
USE YOMGSGEOM, ONLY : TGSGEOM
USE YOMOROG,   ONLY : TOROG
USE TYPE_SPGEOM,ONLY : TSPGEOM
! LAM specific objects
USE YEMDIM   , ONLY : TEDIM
USE YEMGEO   , ONLY : TEGEO
USE YEMMP    , ONLY : TEMMP
USE YEMLAP   , ONLY : TLEP
USE YEMGSL   , ONLY : TEGSL
!
USE YEMLBC_GEO, ONLY :TELBC_GEO
!

IMPLICIT NONE 

PRIVATE

TYPE, PUBLIC :: GEOMETRY
  TYPE(TVERTICAL_GEOM) :: YRVERT_GEOM

  TYPE(TVAB),POINTER     :: YRVAB  ! Geometry restricted vertical hybrid coordinates 0->NFLEVG
  TYPE(TVETA),POINTER    :: YRVETA
  TYPE(TVFE),POINTER     :: YRVFE
  TYPE(TSTA)    :: YRSTA
  TYPE(TLAP)    :: YRLAP
  TYPE(TCSGLEG) :: YRCSGLEG

  TYPE(TDIM)    :: YRDIM
  TYPE(TDIMV)   :: YRDIMV
  TYPE(TMP)     :: YRMP

  TYPE(TGEM)    :: YRGEM

  TYPE(TVSPLIP) :: YRVSPLIP
  TYPE(TVSLETA) :: YRVSLETA
  TYPE(THSLMER) :: YRHSLMER

  TYPE(TCSGEOM), POINTER :: YRCSGEOM(:)
  TYPE(TCSGEOM)          :: YRCSGEOM_NB

  TYPE(TGSGEOM), POINTER :: YRGSGEOM(:)
  TYPE(TGSGEOM)          :: YRGSGEOM_NB

  TYPE(TCSGEOM), POINTER     :: YRCSGEOMAD(:) => NULL()
  TYPE(TCSGEOM)              :: YRCSGEOMAD_NB
  TYPE(TGSGEOM), POINTER     :: YRGSGEOMAD(:) => NULL()
  TYPE(TGSGEOM)              :: YRGSGEOMAD_NB


  TYPE(TOROG),   ALLOCATABLE :: YROROG(:)

  TYPE(TSPGEOM) :: YSPGEOM

  TYPE(TVAB)    :: YVABIO ! I/O full vertical hybrid coordinates 0->NIOLEVG (NIOLEVG >=NFLEVG)

  ! LAM specific objects
  TYPE(TEDIM) :: YREDIM
  TYPE(TEGEO) :: YREGEO
  TYPE(TEMMP) :: YREMP
  TYPE(TLEP)  :: YRELAP
  TYPE(TEGSL) :: YREGSL
!
  TYPE(TELBC_GEO), POINTER :: YRELBC_GEO => NULL()
!

END TYPE GEOMETRY

END MODULE TYPE_GEOMETRY
