PROGRAM WRAP_LAPINEA

USE LOAD_GEOMETRY_MOD
USE LOAD_SL_STRUCT_MOD
USE LOAD_MODEL_GENERAL_CONF_TYPE_MOD
USE LOAD_MODEL_DYNAMICS_TYPE_MOD
USE LOAD_MOD
#ifdef USE_ACC
USE CUDAFOR
#endif

USE LOAD_YOMCT0_MOD
USE LOAD_YOMDYNA_MOD
USE LOAD_YOMCVER_MOD
USE LOAD_YOMCST_MOD
USE LOAD_YOMMP0_MOD
USE LOAD_YOMLUN_MOD
USE LOAD_YOMJFH_MOD

USE XRD_GETOPTIONS

USE PARKIND1

IMPLICIT NONE

TYPE (GEOMETRY)                :: YDGEOMETRY
TYPE (MODEL_GENERAL_CONF_TYPE) :: YDML_GCONF
TYPE (MODEL_DYNAMICS_TYPE)     :: YDML_DYN
TYPE (SL_STRUCT)               :: YDSL

REAL (KIND=JPRB)   , POINTER :: PB1     (:,:)
REAL (KIND=JPRB)   , POINTER :: PB2     (:,:,:)

INTEGER (KIND=JPIM), POINTER :: KVSEPC  (:)
INTEGER (KIND=JPIM), POINTER :: KVSEPL  (:)
REAL (KIND=JPRB)   , POINTER :: PCCO    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PUF     (:,:,:)
REAL (KIND=JPRB)   , POINTER :: PVF     (:,:,:)
INTEGER (KIND=JPIM), POINTER :: KL0     (:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: KLH0    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PLSCAW  (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PRSCAW  (:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: KL0H    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PLSCAWH (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PRSCAWH (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PSCO    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PGFLT1  (:,:,:,:)

REAL (KIND=JPRB)   , POINTER :: PSTACK  (:,:)
INTEGER (KIND=JPIM)          :: KSTSZ
INTEGER (KIND=JPIM)          :: KSTPT

#include "lapinea.intfb.h"

INTEGER (KIND=JPIM), POINTER :: KVSEPC_OUT  (:)
INTEGER (KIND=JPIM), POINTER :: KVSEPL_OUT  (:)
REAL (KIND=JPRB)   , POINTER :: PCCO_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PUF_OUT     (:,:,:)
REAL (KIND=JPRB)   , POINTER :: PVF_OUT     (:,:,:)
INTEGER (KIND=JPIM), POINTER :: KL0_OUT     (:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: KLH0_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PLSCAW_OUT  (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PRSCAW_OUT  (:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: KL0H_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PLSCAWH_OUT (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PRSCAWH_OUT (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PSCO_OUT    (:,:,:,:)
REAL (KIND=JPRB)   , POINTER :: PGFLT1_OUT  (:,:,:,:)

INTEGER :: IDUM, ILUN
INTEGER :: NGPBLKS, NPROMA, NFLEVG
INTEGER :: IST,IEND,IBL,JLON


CHARACTER (LEN=64) :: CLFILE, CLCASE
LOGICAL :: LLDIFF
INTEGER :: ICOUNT, NTIMES, ITIME
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()
INTEGER (KIND=8) :: HEAPSIZE
INTEGER (KIND=4) :: HEAPSIZE4
INTEGER (KIND=4) :: ISTAT


CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT = 0
CALL GETOPTION ("--count", ICOUNT)
HEAPSIZE4 = 0
CALL GETOPTION ("--heapsize", HEAPSIZE4)
NTIMES = 1
CALL GETOPTION ("--times", NTIMES)
CALL CHECKOPTIONS ()

#ifdef USE_ACC
IF (HEAPSIZE4 > 0) THEN
HEAPSIZE = HEAPSIZE4*1024_8*1024_8
ISTAT = CUDADEVICESETLIMIT (CUDALIMITMALLOCHEAPSIZE, HEAPSIZE)
ENDIF

CALL CUDAPROFILERSTOP
#endif

ILUN = 77

#define LOADM(x) CALL O (#x); CALL LOAD_##x (ILUN); CLOSE (ILUN); IDUM

LOADM (YOMCT0) = 0
LOADM (YOMDYNA) = 0
LOADM (YOMCVER) = 0
LOADM (YOMCST) = 0
LOADM (YOMMP0) = 0
LOADM (YOMLUN) = 0
LOADM (YOMJFH) = 0

#undef LOADM

#define LOAD(x) CALL O (#x//".IN"); CALL LOAD (ILUN, x); CLOSE (ILUN); IDUM

LOAD (YDGEOMETRY) = 0 
LOAD (YDML_GCONF) = 0
LOAD (YDSL) = 0
LOAD (YDML_DYN) = 0
LOAD (PB1) = 0
LOAD (PB2) = 0
LOAD (KVSEPC) = 0
LOAD (KVSEPL) = 0
LOAD (PCCO) = 0
LOAD (PUF) = 0
LOAD (PVF) = 0
LOAD (KL0) = 0
LOAD (KLH0) = 0
LOAD (PLSCAW) = 0
LOAD (PRSCAW) = 0
LOAD (KL0H) = 0
LOAD (PLSCAWH) = 0
LOAD (PRSCAWH) = 0
LOAD (PSCO) = 0
LOAD (PGFLT1) = 0

IF (ICOUNT == 0) ICOUNT = SIZE (KVSEPC)

NGPBLKS = MIN (SIZE (KVSEPC), ICOUNT)
NPROMA = YDGEOMETRY%YRDIM%NPROMA
NFLEVG = YDGEOMETRY%YRDIMV%NFLEVG

KSTPT = 1
KSTSZ = (40 + YDML_DYN%YYTSCO%NDIM + YDML_DYN%YRDYN%NSLDIMK) * NPROMA * NFLEVG
ALLOCATE (PSTACK (KSTSZ, NGPBLKS))

#undef LOAD

#ifdef USE_ACC
CALL CUDAPROFILERSTART 
#endif

DO ITIME = 1, NTIMES

#ifdef USE_ACC

!$acc parallel loop gang vector private (IBL, JLON, IST, IEND) collapse (2) vector_length (NPROMA)

  DO IBL = 1, NGPBLKS
   
    DO JLON = 1, NPROMA
    IST=JLON
    IEND=JLON

    CALL LAPINEA(&
     ! --- INPUT --------------------------------------------------------------
     & YDGEOMETRY,YDML_GCONF,YDML_DYN,IST,IEND,YDSL,IBL,PB1,PB2(:,:,IBL),&
     ! --- INPUT/OUTPUT -------------------------------------------------------
     & KVSEPC(IBL),KVSEPL(IBL),&
     ! --- OUTPUT -------------------------------------------------------------
     & PCCO(:,:,:,IBL),PUF(:,:,IBL),PVF(:,:,IBL),&
     & KL0(:,:,:,IBL),KLH0(:,:,:,IBL),PLSCAW(:,:,:,IBL),PRSCAW(:,:,:,IBL),&
     & KL0H(:,:,:,IBL),PLSCAWH(:,:,:,IBL),PRSCAWH(:,:,:,IBL),&
     & PSCO(:,:,:,IBL),PGFLT1(:,:,:,IBL),KSTPT,KSTSZ,PSTACK (:,IBL))
    ENDDO

  ENDDO

!$acc end parallel loop 

#else

!#OMP PARALLEL DO SCHEDULE(DYNAMIC,1)&
!#OMP&PRIVATE(IST,IEND,IBL)
  DO IBL = 1, NGPBLKS
   
    IST=1
    IEND=YDGEOMETRY%YRDIM%NPROMA

    CALL LAPINEA(&
     ! --- INPUT --------------------------------------------------------------
     & YDGEOMETRY,YDML_GCONF,YDML_DYN,IST,IEND,YDSL,IBL,PB1,PB2(:,:,IBL),&
     ! --- INPUT/OUTPUT -------------------------------------------------------
     & KVSEPC(IBL),KVSEPL(IBL),&
     ! --- OUTPUT -------------------------------------------------------------
     & PCCO(:,:,:,IBL),PUF(:,:,IBL),PVF(:,:,IBL),&
     & KL0(:,:,:,IBL),KLH0(:,:,:,IBL),PLSCAW(:,:,:,IBL),PRSCAW(:,:,:,IBL),&
     & KL0H(:,:,:,IBL),PLSCAWH(:,:,:,IBL),PRSCAWH(:,:,:,IBL),&
     & PSCO(:,:,:,IBL),PGFLT1(:,:,:,IBL),KSTPT,KSTSZ,PSTACK (:,IBL))

  ENDDO

!#OMP END PARALLEL DO

#endif

ENDDO

#ifdef USE_ACC
CALL CUDAPROFILERSTOP
#endif


IF (LLDIFF) THEN

#define LOAD(x) CALL O (#x//".OUT"); CALL LOAD (ILUN, x##_OUT); CLOSE (ILUN); IDUM

LOAD (KVSEPC) = 0
LOAD (KVSEPL) = 0
LOAD (PCCO) = 0
LOAD (PUF) = 0
LOAD (PVF) = 0
LOAD (KL0) = 0
LOAD (KLH0) = 0
LOAD (PLSCAW) = 0
LOAD (PRSCAW) = 0
LOAD (KL0H) = 0
LOAD (PLSCAWH) = 0
LOAD (PRSCAWH) = 0
LOAD (PSCO) = 0
LOAD (PGFLT1) = 0

PRINT *, " DIFF "

DO IBL = 1, NGPBLKS

  IF (ASSOCIATED (IDIFFBLOCK)) THEN
    IF (ALL (IDIFFBLOCK /= IBL)) CYCLE
  ENDIF

  PRINT *, " IBLOCK = ", IBL

  CALL DIFF ("KVSEPC", KVSEPC_OUT (IBL), KVSEPC (IBL))
  CALL DIFF ("KVSEPL", KVSEPL_OUT (IBL), KVSEPL (IBL))
  CALL DIFF ("PCCO", PCCO_OUT (:,:,:,IBL), PCCO (:,:,:,IBL))
ENDDO


ENDIF


CONTAINS

SUBROUTINE O (CDFILE)

INTEGER, PARAMETER :: MYPROC = 1

CHARACTER (LEN=*) :: CDFILE

WRITE (CLFILE, '(I3.3)') MYPROC
CLFILE=TRIM (CDFILE)//"."//TRIM (CLFILE)

OPEN (ILUN, FILE=TRIM (CLCASE)//"/"//TRIM (CLFILE), FORM='UNFORMATTED')

END SUBROUTINE

END

