MODULE COPY_MODEL_GENERAL_CONF_TYPE_MOD

USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_GENERAL_CONF_TYPE
END INTERFACE

CONTAINS

SUBROUTINE COPY_MODEL_GENERAL_CONF_TYPE (YD)
USE COPY_TDIMF_MOD
USE COPY_TRIP_MOD
USE COPY_TYPE_GFLD_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN) :: YD

CALL COPY (YD%YRDIMF)

CALL COPY (YD%YGFL)

CALL COPY (YD%YRRIP)

!$acc serial present (YD)
PRINT *, " CSTOP = ", YD%YRRIP%CSTOP
!$acc end serial

END SUBROUTINE

END MODULE
