MODULE LOAD_TVERTICAL_GEOM_MOD

USE YOMVERT, ONLY : TVERTICAL_GEOM

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVERTICAL_GEOM
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVERTICAL_GEOM (KLUN, YD)
USE LOAD_TVAB_MOD
USE LOAD_TVETA_MOD
USE LOAD_TVFE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVERTICAL_GEOM), INTENT (OUT) :: YD

CALL LOAD (KLUN, YD%YRVAB)
CALL LOAD (KLUN, YD%YRVETA)
CALL LOAD (KLUN, YD%YRVFE)
END SUBROUTINE


END MODULE
