MODULE LOAD_TEDIM_MOD

USE YEMDIM, ONLY : TEDIM

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEDIM
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TEDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEDIM), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LNISMAX, LNISNAX
READ (KLUN) YD%NSECPLG
READ (KLUN) YD%NBZONG
READ (KLUN) YD%NBZONL
READ (KLUN) YD%NNOEXTZG
READ (KLUN) YD%NNOEXTZL
READ (KLUN) LNISMAX
IF (LNISMAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NISMAX (IL1(1):IU1(1)))
  READ (KLUN) YD%NISMAX
ELSE
  NULLIFY (YD%NISMAX)
ENDIF
READ (KLUN) LNISNAX
IF (LNISNAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NISNAX (IL1(1):IU1(1)))
  READ (KLUN) YD%NISNAX
ELSE
  NULLIFY (YD%NISNAX)
ENDIF
READ (KLUN) YD%LBIPINCI
READ (KLUN) YD%NBIPINCIX
READ (KLUN) YD%NBIPINCIY
READ (KLUN) YD%NEDOM
END SUBROUTINE


END MODULE
