MODULE LOAD_TDIM_MOD

USE YOMDIM, ONLY : TDIM

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIM
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIM), INTENT (OUT) :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LNDLUNL, LNDLUXL
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDGLL
READ (KLUN) YD%NDGNH
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGSAFPH
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NDGENFPH
READ (KLUN) YD%NDGUNG
READ (KLUN) YD%NDGUXG
READ (KLUN) YD%NDGUNL
READ (KLUN) YD%NDGUXL
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NSTENCILWIDE
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NDLSM
READ (KLUN) YD%NDLUNG
READ (KLUN) YD%NDLUXG
READ (KLUN) LNDLUNL
IF (LNDLUNL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NDLUNL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NDLUNL
ENDIF
READ (KLUN) LNDLUXL
IF (LNDLUXL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NDLUXL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NDLUXL
ENDIF
READ (KLUN) YD%NPROMA
READ (KLUN) YD%NPROMA9
READ (KLUN) YD%NPROMM
READ (KLUN) YD%NPROMM9
READ (KLUN) YD%NPROMNH
READ (KLUN) YD%NPROMNH9
READ (KLUN) YD%NGPBLKS
READ (KLUN) YD%LOPTPROMA
READ (KLUN) YD%NRESOL
READ (KLUN) YD%NSMAX
READ (KLUN) YD%NMSMAX
READ (KLUN) YD%NVARMAX
READ (KLUN) YD%NSEFRE
READ (KLUN) YD%NSPECG
READ (KLUN) YD%NSPEC2G
READ (KLUN) YD%NSPEC
READ (KLUN) YD%NSPEC2
READ (KLUN) YD%NSPEC2MX
READ (KLUN) YD%NCMAX
READ (KLUN) YD%NUMP
READ (KLUN) YD%NUMCP
END SUBROUTINE


END MODULE
