MODULE LOAD_THSLMER_MOD

USE YOMHSLMER, ONLY : THSLMER

INTERFACE LOAD
MODULE PROCEDURE LOAD_THSLMER
END INTERFACE

CONTAINS

SUBROUTINE LOAD_THSLMER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (THSLMER), INTENT (OUT) :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW
READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RIPI
ENDIF
READ (KLUN) LRSLD
IF (LRSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RSLD
ENDIF
READ (KLUN) LRSLDW
IF (LRSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RSLDW
ENDIF
READ (KLUN) LR3DTW
IF (LR3DTW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%R3DTW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%R3DTW
ENDIF
END SUBROUTINE


END MODULE
