MODULE LOAD_TVAB_MOD

USE YOMVERT, ONLY : TVAB

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVAB
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVAB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVAB), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB
READ (KLUN) LVALH
IF (LVALH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VALH (IL1(1):IU1(1)))
  READ (KLUN) YD%VALH
ENDIF
READ (KLUN) LVBH
IF (LVBH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VBH (IL1(1):IU1(1)))
  READ (KLUN) YD%VBH
ENDIF
READ (KLUN) LVAH
IF (LVAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VAH (IL1(1):IU1(1)))
  READ (KLUN) YD%VAH
ENDIF
READ (KLUN) LVC
IF (LVC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VC (IL1(1):IU1(1)))
  READ (KLUN) YD%VC
ENDIF
READ (KLUN) LVAF
IF (LVAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VAF (IL1(1):IU1(1)))
  READ (KLUN) YD%VAF
ENDIF
READ (KLUN) LVBF
IF (LVBF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VBF (IL1(1):IU1(1)))
  READ (KLUN) YD%VBF
ENDIF
READ (KLUN) LVDELA
IF (LVDELA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VDELA (IL1(1):IU1(1)))
  READ (KLUN) YD%VDELA
ENDIF
READ (KLUN) LVDELB
IF (LVDELB) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VDELB (IL1(1):IU1(1)))
  READ (KLUN) YD%VDELB
ENDIF
END SUBROUTINE


END MODULE
