MODULE LOAD_TVSLETA_MOD

USE YOMVSLETA, ONLY : TVSLETA

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVSLETA
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TVSLETA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
READ (KLUN) LVCUICO
IF (LVCUICO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VCUICO
ENDIF
READ (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICOH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VCUICOH
ENDIF
READ (KLUN) LVSLD
IF (LVSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VSLD
ENDIF
READ (KLUN) LVSLDH
IF (LVSLDH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLDH (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%VSLDH
ENDIF
READ (KLUN) LVSLDW
IF (LVSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%VSLDW
ENDIF
READ (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDWH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%VSLDWH
ENDIF
READ (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRDETAR (IL1(1):IU1(1)))
  READ (KLUN) YD%VRDETAR
ENDIF
READ (KLUN) YD%NRLEVX
READ (KLUN) YD%VRLEVX
READ (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTF (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTF
ENDIF
READ (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTH (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE


END MODULE
