MODULE LOAD_TEGEO_MOD

USE YEMGEO, ONLY : TEGEO

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGEO
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TEGEO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGEO), INTENT (OUT) :: YD

READ (KLUN) YD%ERPK
READ (KLUN) YD%ELON1
READ (KLUN) YD%ELAT1
READ (KLUN) YD%ELON2
READ (KLUN) YD%ELAT2
READ (KLUN) YD%ELON0
READ (KLUN) YD%ELAT0
READ (KLUN) YD%ELONC
READ (KLUN) YD%ELATC
READ (KLUN) YD%EDELX
READ (KLUN) YD%EDELY
READ (KLUN) YD%ELX
READ (KLUN) YD%ELY
READ (KLUN) YD%EXWN
READ (KLUN) YD%EYWN
READ (KLUN) YD%RCORI_ACAD
READ (KLUN) YD%RLAT_ACAD
READ (KLUN) YD%RLON_ACAD
READ (KLUN) YD%LMAP
READ (KLUN) YD%LMRT
READ (KLUN) YD%LREDEL_IN_METRES
END SUBROUTINE


END MODULE
