MODULE LOAD_TSTA_MOD

USE YOMSTA, ONLY : TSTA

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSTA
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TSTA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSTA), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ
READ (KLUN) LSTPREH
IF (LSTPREH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPREH (IL1(1):IU1(1)))
  READ (KLUN) YD%STPREH
ENDIF
READ (KLUN) LSTPRE
IF (LSTPRE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPRE (IL1(1):IU1(1)))
  READ (KLUN) YD%STPRE
ENDIF
READ (KLUN) LSTPHI
IF (LSTPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STPHI (IL1(1):IU1(1)))
  READ (KLUN) YD%STPHI
ENDIF
READ (KLUN) LSTTEM
IF (LSTTEM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STTEM (IL1(1):IU1(1)))
  READ (KLUN) YD%STTEM
ENDIF
READ (KLUN) LSTDEN
IF (LSTDEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STDEN (IL1(1):IU1(1)))
  READ (KLUN) YD%STDEN
ENDIF
READ (KLUN) LSTZ
IF (LSTZ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%STZ (IL1(1):IU1(1)))
  READ (KLUN) YD%STZ
ENDIF
END SUBROUTINE


END MODULE
