MODULE LOAD_MODEL_DYNAMICS_TYPE_MOD

USE MODEL_DYNAMICS_MOD, ONLY : MODEL_DYNAMICS_TYPE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DYNAMICS_TYPE
END INTERFACE

CONTAINS

SUBROUTINE LOAD_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE LOAD_SL_STRUCT_MOD
USE LOAD_TCCO_MOD
USE LOAD_TDYN_MOD
USE LOAD_TEDYN_MOD
USE LOAD_TLSCAW_MOD
USE LOAD_TPTRGPPC_MOD
USE LOAD_TPTRSLB1_MOD
USE LOAD_TPTRSLB15_MOD
USE LOAD_TPTRSLB2_MOD
USE LOAD_TRSCAW_MOD
USE LOAD_TSCO_MOD
USE LOAD_TSLREP_MOD
USE LOAD_TSPNG_MOD
USE LOAD_TTNH_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (OUT) :: YD

CALL LOAD (KLUN, YD%YRDYN)
CALL LOAD (KLUN, YD%YREDYN)
CALL LOAD (KLUN, YD%YRSPNG)
CALL LOAD (KLUN, YD%YRPTRGPPC)
CALL LOAD (KLUN, YD%YYTLSCAW)
CALL LOAD (KLUN, YD%YYTLSCAWH)
CALL LOAD (KLUN, YD%YYTRSCAW)
CALL LOAD (KLUN, YD%YYTRSCAWH)
CALL LOAD (KLUN, YD%YYTSCO)
CALL LOAD (KLUN, YD%YYTCCO)
CALL LOAD (KLUN, YD%YRSLREP)
CALL LOAD (KLUN, YD%YRPTRSLB1)
CALL LOAD (KLUN, YD%YRPTRSLB2)
CALL LOAD (KLUN, YD%YRPTRSLB15)
CALL LOAD (KLUN, YD%YRTNH)
CALL LOAD (KLUN, YD%YRSL)
CALL LOAD (KLUN, YD%YRAD)
END SUBROUTINE


END MODULE
