MODULE LOAD_TEDYN_MOD

USE YEMDYN, ONLY : TEDYN

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEDYN
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TEDYN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEDYN), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LRDIDIVE, LRDIGFLE, LRDIPDE, LRDISPE, LRDITE, LRDIVDE, LRDIVORE, LRDSDIVE, LRDSVDE, LRDSVORE, LREFILD, LREFILV
READ (KLUN) LRDIVORE
IF (LRDIVORE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVORE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIVORE
ENDIF
READ (KLUN) LRDIDIVE
IF (LRDIDIVE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIDIVE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIDIVE
ENDIF
READ (KLUN) LRDITE
IF (LRDITE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDITE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDITE
ENDIF
READ (KLUN) LRDIGFLE
IF (LRDIGFLE) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDIGFLE (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDIGFLE
ENDIF
READ (KLUN) LRDIPDE
IF (LRDIPDE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIPDE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIPDE
ENDIF
READ (KLUN) LRDIVDE
IF (LRDIVDE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVDE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIVDE
ENDIF
READ (KLUN) LRDISPE
IF (LRDISPE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RDISPE (IL1(1):IU1(1)))
  READ (KLUN) YD%RDISPE
ENDIF
READ (KLUN) LRDSVORE
IF (LRDSVORE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVORE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSVORE
ENDIF
READ (KLUN) LRDSDIVE
IF (LRDSDIVE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSDIVE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSDIVE
ENDIF
READ (KLUN) LRDSVDE
IF (LRDSVDE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVDE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSVDE
ENDIF
READ (KLUN) LREFILV
IF (LREFILV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%REFILV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%REFILV
ENDIF
READ (KLUN) LREFILD
IF (LREFILD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%REFILD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%REFILD
ENDIF
READ (KLUN) YD%LESIDG
READ (KLUN) YD%RTHRESIDG
READ (KLUN) YD%XMALD
READ (KLUN) YD%TCDIS
END SUBROUTINE


END MODULE
