MODULE LOAD_TDYN_MOD

USE YOMDYN, ONLY : TDYN

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDYN
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TDYN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYN), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG, LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRKRF, LSIALPH, LSIB, LSIBI, LSIDELP, LSIDPHI, LSIFAC, LSIFACI, LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSIMI, LSIMO, LSIRDEL, LSITLAF, LSITLAH, LSITRAM, LSIVP, LSI_ILAPKSSI, LSLHDA, LSLHDD0
READ (KLUN) YD%REPS1
READ (KLUN) YD%REPS2
READ (KLUN) YD%REPSM1
READ (KLUN) YD%REPSM2
READ (KLUN) YD%REPSP1
READ (KLUN) YD%HDIRVOR
READ (KLUN) YD%HDIRDIV
READ (KLUN) YD%HDIRT
READ (KLUN) YD%HDIRQ
READ (KLUN) YD%HDIRO3
READ (KLUN) YD%HDIRPD
READ (KLUN) YD%HDIRVD
READ (KLUN) YD%HDIRSP
READ (KLUN) YD%HRDIRVOR
READ (KLUN) YD%HRDIRDIV
READ (KLUN) YD%HRDIRT
READ (KLUN) YD%HRDIRQ
READ (KLUN) YD%HRDIRO3
READ (KLUN) YD%HRDIRPD
READ (KLUN) YD%HRDIRVD
READ (KLUN) YD%HRDIRSP
READ (KLUN) YD%RRDXTAU
READ (KLUN) YD%RDAMPVOR
READ (KLUN) YD%RDAMPDIV
READ (KLUN) YD%RDAMPT
READ (KLUN) YD%RDAMPQ
READ (KLUN) YD%RDAMPO3
READ (KLUN) YD%RDAMPPD
READ (KLUN) YD%RDAMPVD
READ (KLUN) YD%RDAMPSP
READ (KLUN) YD%LNEWHD
READ (KLUN) YD%REXPDH
READ (KLUN) YD%FRANDH
READ (KLUN) YD%SLEVDH
READ (KLUN) YD%SLEVDH1
READ (KLUN) YD%SLEVDH2
READ (KLUN) YD%SLEVDH3
READ (KLUN) YD%NSREFDH
READ (KLUN) YD%RATIO_HDI_TOP
READ (KLUN) YD%NPROFILEHD
READ (KLUN) YD%RPROFHDBT
READ (KLUN) YD%RPROFHDTP
READ (KLUN) YD%RPROFHDMX
READ (KLUN) YD%RPROFHDEX
READ (KLUN) YD%LRDISPE_EC
READ (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIVOR
ENDIF
READ (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIDIV
ENDIF
READ (KLUN) LRDITG
IF (LRDITG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDITG (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDITG
ENDIF
READ (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDIGFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDIGFL
ENDIF
READ (KLUN) LRDIPD
IF (LRDIPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIPD
ENDIF
READ (KLUN) LRDIVD
IF (LRDIVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDIVD
ENDIF
READ (KLUN) LRDISP
IF (LRDISP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RDISP (IL1(1):IU1(1)))
  READ (KLUN) YD%RDISP
ENDIF
READ (KLUN) LRDHI
IF (LRDHI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDHI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDHI
ENDIF
READ (KLUN) YD%LSTRHD
READ (KLUN) YD%HDTIME_STRHD
READ (KLUN) YD%LTOP_VOR
READ (KLUN) YD%NTOP_VOR_TRUNC
READ (KLUN) YD%NTOP_VOR_BOT
READ (KLUN) LSLHDA
IF (LSLHDA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHDA (IL1(1):IU1(1)))
  READ (KLUN) YD%SLHDA
ENDIF
READ (KLUN) YD%SLHDA0
READ (KLUN) YD%SLHDA0T
READ (KLUN) YD%SLHDB
READ (KLUN) YD%SLHDBT
READ (KLUN) LSLHDD0
IF (LSLHDD0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHDD0 (IL1(1):IU1(1)))
  READ (KLUN) YD%SLHDD0
ENDIF
READ (KLUN) YD%SLHDD00
READ (KLUN) YD%SLHDD00T
READ (KLUN) YD%SLHDDIV
READ (KLUN) YD%SLHDRATDDIV
READ (KLUN) YD%SLHDHOR
READ (KLUN) YD%LSLHDHEAT
READ (KLUN) YD%HDSRVOR
READ (KLUN) YD%HDSRDIV
READ (KLUN) YD%HDSRVD
READ (KLUN) YD%HRDSRVOR
READ (KLUN) YD%HRDSRDIV
READ (KLUN) YD%HRDSRVD
READ (KLUN) YD%RDAMPVORS
READ (KLUN) YD%RDAMPDIVS
READ (KLUN) YD%RDAMPVDS
READ (KLUN) YD%RDAMPHDS
READ (KLUN) YD%REXPDHS
READ (KLUN) YD%SLEVDHS
READ (KLUN) YD%SLEVDHS1
READ (KLUN) YD%SLEVDHS2
READ (KLUN) YD%SDRED
READ (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSVOR
ENDIF
READ (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSDIV
ENDIF
READ (KLUN) LRDSVD
IF (LRDSVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RDSVD
ENDIF
READ (KLUN) LRDHS
IF (LRDHS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDHS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%RDHS
ENDIF
READ (KLUN) YD%LRFRIC
READ (KLUN) YD%LRFRICISOTR
READ (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIT (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORDIT
ENDIF
READ (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIH (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORDIH
ENDIF
READ (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIF (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORDIF
ENDIF
READ (KLUN) YD%VMAX1
READ (KLUN) YD%VMAX2
READ (KLUN) YD%RMAX_D3
READ (KLUN) YD%LBOUND_D3
READ (KLUN) LRKRF
IF (LRKRF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RKRF (IL1(1):IU1(1)))
  READ (KLUN) YD%RKRF
ENDIF
READ (KLUN) YD%NMAXLEVRF
READ (KLUN) YD%RRFZ1
READ (KLUN) YD%RRFPLM
READ (KLUN) YD%RRFTAU
READ (KLUN) YD%RTEMRB
READ (KLUN) YD%NRUBC
READ (KLUN) YD%LSIDG
READ (KLUN) YD%BETADT
READ (KLUN) YD%RBT
READ (KLUN) YD%RBTS2
READ (KLUN) YD%REFGEO
READ (KLUN) YD%SIPR
READ (KLUN) YD%SITR
READ (KLUN) YD%SITRA
READ (KLUN) YD%SITRUB
READ (KLUN) YD%SIPRUB
READ (KLUN) YD%SITIME
READ (KLUN) YD%SIRPRG
READ (KLUN) YD%SIRPRN
READ (KLUN) YD%NSITER
READ (KLUN) YD%NCURRENT_ITER
READ (KLUN) YD%LRHDI_LASTITERPC
READ (KLUN) YD%NITERHELM
READ (KLUN) YD%NOPT_SITRA
READ (KLUN) LSIALPH
IF (LSIALPH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIALPH (IL1(1):IU1(1)))
  READ (KLUN) YD%SIALPH
ENDIF
READ (KLUN) LSILNPR
IF (LSILNPR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SILNPR (IL1(1):IU1(1)))
  READ (KLUN) YD%SILNPR
ENDIF
READ (KLUN) LSIDELP
IF (LSIDELP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDELP (IL1(1):IU1(1)))
  READ (KLUN) YD%SIDELP
ENDIF
READ (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIRDEL (IL1(1):IU1(1)))
  READ (KLUN) YD%SIRDEL
ENDIF
READ (KLUN) LSITLAH
IF (LSITLAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAH (IL1(1):IU1(1)))
  READ (KLUN) YD%SITLAH
ENDIF
READ (KLUN) LSITLAF
IF (LSITLAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAF (IL1(1):IU1(1)))
  READ (KLUN) YD%SITLAF
ENDIF
READ (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDPHI (IL1(1):IU1(1)))
  READ (KLUN) YD%SIDPHI
ENDIF
READ (KLUN) LSIB
IF (LSIB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIB (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIB
ENDIF
READ (KLUN) LSIMO
IF (LSIMO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIMO (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIMO
ENDIF
READ (KLUN) LSIMI
IF (LSIMI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIMI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIMI
ENDIF
READ (KLUN) LSIVP
IF (LSIVP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIVP (IL1(1):IU1(1)))
  READ (KLUN) YD%SIVP
ENDIF
READ (KLUN) LSIHEG
IF (LSIHEG) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEG (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEG
ENDIF
READ (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEG2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEG2
ENDIF
READ (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEGB (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEGB
ENDIF
READ (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEGB2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SIHEGB2
ENDIF
READ (KLUN) LSIFAC
IF (LSIFAC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIFAC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIFAC
ENDIF
READ (KLUN) LSIFACI
IF (LSIFACI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIFACI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIFACI
ENDIF
READ (KLUN) LSI_ILAPKSSI
IF (LSI_ILAPKSSI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SI_ILAPKSSI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%SI_ILAPKSSI
ENDIF
READ (KLUN) LSITRAM
IF (LSITRAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITRAM (IL1(1):IU1(1)))
  READ (KLUN) YD%SITRAM
ENDIF
READ (KLUN) YD%VNORM
READ (KLUN) YD%NVLAG
READ (KLUN) YD%NWLAG
READ (KLUN) YD%NTLAG
READ (KLUN) YD%NSPDLAG
READ (KLUN) YD%NSVDLAG
READ (KLUN) YD%NSPLTHOI
READ (KLUN) YD%LSPLTHOIGFL
READ (KLUN) YD%NSLDIMK
READ (KLUN) YD%NITMP
READ (KLUN) YD%VETAON
READ (KLUN) YD%VETAOX
READ (KLUN) YD%LSETTLSVF
READ (KLUN) YD%LSETFSTAT
READ (KLUN) YD%RW2TLFF
READ (KLUN) YD%VESL
READ (KLUN) YD%XIDT
READ (KLUN) YD%LQMW
READ (KLUN) YD%LQMHW
READ (KLUN) YD%LQMT
READ (KLUN) YD%LQMHT
READ (KLUN) YD%LQMP
READ (KLUN) YD%LQMHP
READ (KLUN) YD%LQMPD
READ (KLUN) YD%LQMHPD
READ (KLUN) YD%LQMVD
READ (KLUN) YD%LQMHVD
READ (KLUN) YD%LADVF
READ (KLUN) YD%LIMPF
READ (KLUN) YD%L2TLFF
READ (KLUN) YD%RCMSLP0
READ (KLUN) YD%NCOMP_CVGQ
READ (KLUN) YD%LSVTSM
READ (KLUN) YD%RPRES_SVTSM
READ (KLUN) YD%RPRES_SETTLSVF
READ (KLUN) YD%NFLEVSF
READ (KLUN) YD%RSCALE
READ (KLUN) YD%RSCALEOFF
READ (KLUN) YD%LHDIFFM
READ (KLUN) YD%LSPECVIS
READ (KLUN) YD%NDIFFACT
READ (KLUN) YD%LGPSTRESS
READ (KLUN) YD%RCLSTRESS
READ (KLUN) YD%RCLPOLE
READ (KLUN) YD%NVSEPC
READ (KLUN) YD%NVSEPL
READ (KLUN) YD%LFINDVSEP
READ (KLUN) YD%LMASCOR
READ (KLUN) YD%LMASDRY
READ (KLUN) YD%LGPMASCOR
READ (KLUN) YD%NGPMASCOR
READ (KLUN) YD%GPMASSI
READ (KLUN) YD%GMASSI
READ (KLUN) YD%GMASS0
READ (KLUN) YD%GMASSINC
READ (KLUN) LSIBI
IF (LSIBI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIBI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%SIBI
ENDIF
END SUBROUTINE


END MODULE
