MODULE LOAD_TSCO_MOD

USE INTDYNSL_MOD, ONLY : TSCO

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSCO
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TSCO (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSCO), INTENT (OUT) :: YD

READ (KLUN) YD%M_COSCO
READ (KLUN) YD%M_SINCO
READ (KLUN) YD%M_SINLA
READ (KLUN) YD%M_COPHI
READ (KLUN) YD%NDIM
END SUBROUTINE


END MODULE
