MODULE LOAD_TGSGEOM_MOD

USE YOMGSGEOM, ONLY : TGSGEOM

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGSGEOM
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TGSGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGSGEOM), INTENT (OUT) :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL, LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC
READ (KLUN) LRCORI
IF (LRCORI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORI (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORI
ELSE
  NULLIFY (YD%RCORI)
ENDIF
READ (KLUN) LRCORIC
IF (LRCORIC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORIC (IL1(1):IU1(1)))
  READ (KLUN) YD%RCORIC
ELSE
  NULLIFY (YD%RCORIC)
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GEMU (IL1(1):IU1(1)))
  READ (KLUN) YD%GEMU
ELSE
  NULLIFY (YD%GEMU)
ENDIF
READ (KLUN) LGSQM2
IF (LGSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GSQM2 (IL1(1):IU1(1)))
  READ (KLUN) YD%GSQM2
ELSE
  NULLIFY (YD%GSQM2)
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAM (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAM
ELSE
  NULLIFY (YD%GELAM)
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAT (IL1(1):IU1(1)))
  READ (KLUN) YD%GELAT
ELSE
  NULLIFY (YD%GELAT)
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GECLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GECLO
ELSE
  NULLIFY (YD%GECLO)
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GESLO (IL1(1):IU1(1)))
  READ (KLUN) YD%GESLO
ELSE
  NULLIFY (YD%GESLO)
ENDIF
READ (KLUN) LGM
IF (LGM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GM (IL1(1):IU1(1)))
  READ (KLUN) YD%GM
ELSE
  NULLIFY (YD%GM)
ENDIF
READ (KLUN) LGMAPPA
IF (LGMAPPA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GMAPPA (IL1(1):IU1(1)))
  READ (KLUN) YD%GMAPPA
ELSE
  NULLIFY (YD%GMAPPA)
ENDIF
READ (KLUN) LGOMVRL
IF (LGOMVRL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GOMVRL (IL1(1):IU1(1)))
  READ (KLUN) YD%GOMVRL
ELSE
  NULLIFY (YD%GOMVRL)
ENDIF
READ (KLUN) LGOMVRM
IF (LGOMVRM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GOMVRM (IL1(1):IU1(1)))
  READ (KLUN) YD%GOMVRM
ELSE
  NULLIFY (YD%GOMVRM)
ENDIF
READ (KLUN) LGNORDL
IF (LGNORDL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDL (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDL
ELSE
  NULLIFY (YD%GNORDL)
ENDIF
READ (KLUN) LGNORDM
IF (LGNORDM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDM (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDM
ELSE
  NULLIFY (YD%GNORDM)
ENDIF
READ (KLUN) LGNORDLCL
IF (LGNORDLCL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDLCL (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDLCL
ELSE
  NULLIFY (YD%GNORDLCL)
ENDIF
READ (KLUN) LGNORDMCL
IF (LGNORDMCL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDMCL (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDMCL
ELSE
  NULLIFY (YD%GNORDMCL)
ENDIF
READ (KLUN) LGNORDMCM
IF (LGNORDMCM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GNORDMCM (IL1(1):IU1(1)))
  READ (KLUN) YD%GNORDMCM
ELSE
  NULLIFY (YD%GNORDMCM)
ENDIF
READ (KLUN) LGAW
IF (LGAW) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GAW (IL1(1):IU1(1)))
  READ (KLUN) YD%GAW
ELSE
  NULLIFY (YD%GAW)
ENDIF
READ (KLUN) LNGPLAT
IF (LNGPLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGPLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NGPLAT
ELSE
  NULLIFY (YD%NGPLAT)
ENDIF
READ (KLUN) LNUNIQUEGP
IF (LNUNIQUEGP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUNIQUEGP (IL1(1):IU1(1)))
  READ (KLUN) YD%NUNIQUEGP
ELSE
  NULLIFY (YD%NUNIQUEGP)
ENDIF
END SUBROUTINE


END MODULE
